
package FORMULARIOS;

import BEANS.Gestion;
import BEANS.Globales;
import BEANS.Usuario;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frm_Cartera_Quit extends javax.swing.JDialog {
    
    void cargar(){
    try{

    cbo_tipcon.removeAllItems();
    cbo_usuario.removeAllItems();

    Usuario usu=new Usuario();
    ArrayList lista=new ArrayList();
    lista=usu.listado_teleoperadores();  

    for(int i=0;i<lista.size();i++){
    usu=(Usuario)lista.get(i);  
    cbo_usuario.addItem(usu.getId_codusu() + " - " + usu.getC_nomusu());
    }cbo_usuario.addItem("Todos");
    cbo_usuario.setSelectedItem("Todos");
    
    cbo_tipcon.addItem("01 - Contacto Directo");
    cbo_tipcon.addItem("02 - Contacto Indirecto");
    cbo_tipcon.addItem("03 - No Contacto");
    cbo_tipcon.setSelectedItem("03 - No Contacto");
           
    }catch(Exception ioE){
    JOptionPane.showMessageDialog(null, ioE);    
    }
            
    }


    public frm_Cartera_Quit(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ((javax.swing.JSpinner.DateEditor)dtpf_fecpro.getEditor()).getTextField().setEditable(false);
        this.cargar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dtpf_fecpro = new javax.swing.JSpinner();
        cbo_tipres = new javax.swing.JComboBox();
        cbo_tipcon = new javax.swing.JComboBox();
        cbo_usuario = new javax.swing.JComboBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_buscar = new javax.swing.JButton();
        btn_quitar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbl_nroreg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quitar Contratos");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel1.setText("F. Proceso :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 18, 80, 17);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel2.setText("Tip. Respuesta :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 48, 102, 17);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel3.setText("Tip. Contact :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(197, 19, 87, 17);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel4.setText("Operador :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(455, 20, 72, 17);

        dtpf_fecpro.setModel(new javax.swing.SpinnerDateModel());
        dtpf_fecpro.setEditor(new javax.swing.JSpinner.DateEditor(dtpf_fecpro, "dd/MM/yyyy"));
        jPanel1.add(dtpf_fecpro);
        dtpf_fecpro.setBounds(95, 17, 95, 22);

        cbo_tipres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_tipres);
        cbo_tipres.setBounds(122, 45, 580, 22);

        cbo_tipcon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_tipcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_tipconActionPerformed(evt);
            }
        });
        jPanel1.add(cbo_tipcon);
        cbo_tipcon.setBounds(285, 17, 160, 22);

        cbo_usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_usuario);
        cbo_usuario.setBounds(535, 18, 280, 22);

        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(10, 75, 805, 25);

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "f_fproceso", "c_codcent", "c_nrodoc", "c_nombre", "c_contrato", "n_idxges", "c_destcon", "c_destres", "f_fecresp", "c_destres_sub", "c_obsges", "c_nomusu", "id_codusu", "id_codtcon", "id_codtres"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(77);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(230);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(70);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(110);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(220);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(77);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(270);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(12).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(13).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(14).setPreferredWidth(100);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 805, 300);

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar);
        btn_buscar.setBounds(322, 420, 80, 30);

        btn_quitar.setText("Quitar");
        btn_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quitarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quitar);
        btn_quitar.setBounds(415, 420, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 5, 832, 455);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel14.setText("Nº Registros :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(15, 5, 85, 17);

        lbl_nroreg.setEditable(false);
        lbl_nroreg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lbl_nroreg.setText("0");
        jPanel3.add(lbl_nroreg);
        lbl_nroreg.setBounds(105, 4, 60, 22);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 467, 843, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_tipconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_tipconActionPerformed
       try{
        String id_codtcon="";
        
        id_codtcon=String.valueOf(cbo_tipcon.getSelectedItem()).substring(0, 2);
      

        cbo_tipres.removeAllItems();
        Gestion llm=new Gestion();
        ArrayList lista=new ArrayList();
        lista=llm.Respuesta_llam(id_codtcon);

        for(int i=0;i<lista.size();i++){
        llm=(Gestion)lista.get(i);
        cbo_tipres.addItem(llm.getId_codtres() + " - " + llm.getC_destres());
        }cbo_tipres.setSelectedItem("SG00 - Sin Gestion");

        }catch(Exception ioE){

        }
    }//GEN-LAST:event_cbo_tipconActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
    try{
    int index;
    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
    String f_fproceso, id_codtcon, id_codtres, id_codusu;

    f_fproceso=sdf.format(dtpf_fecpro.getValue());    
    id_codtcon=(cbo_tipcon.getSelectedItem() + "").substring(0, 2);     
    id_codtres=String.valueOf(cbo_tipres.getSelectedItem() + "").substring(0, 4).trim();
    index=(cbo_usuario.getSelectedItem() + "").indexOf(" - ", 0);

    if(cbo_usuario.getSelectedItem()!="Todos"){
    id_codusu=(cbo_usuario.getSelectedItem() + "").substring(0, index);
    }else{
    id_codusu="";
    }   

    Gestion ges=new Gestion();
    Globales glo=new Globales();
    ArrayList lista=new ArrayList();
    lista=ges.gestion_llamada_quitar(f_fproceso, glo.getId_codper(), id_codtcon, id_codtres, id_codusu);
    lbl_nroreg.setText(lista.size() + "");
    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    m.setRowCount(lista.size());

    for(int i=0;i<lista.size();i++){
    ges=(Gestion)lista.get(i);
    m.setValueAt(ges.getF_fproceso(), i, 0);
    m.setValueAt(ges.getC_codcent(), i, 1);
    m.setValueAt(ges.getC_nrodoc(), i, 2);
    m.setValueAt(ges.getC_nombre(), i, 3);
    m.setValueAt(ges.getC_contrato(), i, 4);
    m.setValueAt(ges.getN_idxges(), i, 5);
    m.setValueAt(ges.getC_destcon(), i, 6);
    m.setValueAt(ges.getC_destres(), i, 7);
    m.setValueAt(ges.getF_fecresp(), i, 8);
    m.setValueAt(ges.getC_destres_sub(), i, 9);
    m.setValueAt(ges.getC_obsges(), i, 10);
    m.setValueAt(ges.getC_nomusu(), i, 11);
    m.setValueAt(ges.getId_codusu(), i, 12);
    m.setValueAt(ges.getId_codtcon(), i, 13);
    m.setValueAt(ges.getId_codtres(), i, 14);
    }jTable1.setModel(m);
    }catch(Exception ioE){
    JOptionPane.showMessageDialog(null, ioE);
    }
}//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quitarActionPerformed
       try{
       if(jTable1.getRowCount()>0){

       int res=JOptionPane.showConfirmDialog(null, "Seguro de Eliminar Registro","Informacion",JOptionPane.YES_NO_OPTION);
       if(res==1){
       return;
       }else{
       Gestion ges=new Gestion();

       String f_fproceso, c_contrato, c_codcent, id_codtcon, id_codtres, id_codusu, n_idxges;

       for(int i=0;i<jTable1.getRowCount();i++){
       f_fproceso=String.valueOf(jTable1.getValueAt(i, 0)).substring(0, 10) + " 00:00:00.000";
       c_contrato=jTable1.getValueAt(i, 4) + "";
       c_codcent=jTable1.getValueAt(i, 1) + "";
       id_codtcon=jTable1.getValueAt(i, 13) + "";
       id_codtres=jTable1.getValueAt(i, 14)+ "";
       id_codusu=jTable1.getValueAt(i, 12) + "";
       n_idxges=jTable1.getValueAt(i, 5) +"";

       ges.elimina_registro_llamada(f_fproceso, c_contrato, c_codcent, id_codtcon, id_codtres, id_codusu, n_idxges);
       
       }btn_buscarActionPerformed(evt);
       }
       }
       }catch(Exception e){
       JOptionPane.showMessageDialog(null, e.getMessage());
       }
}//GEN-LAST:event_btn_quitarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_quitar;
    private javax.swing.JComboBox cbo_tipcon;
    private javax.swing.JComboBox cbo_tipres;
    private javax.swing.JComboBox cbo_usuario;
    private javax.swing.JSpinner dtpf_fecpro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lbl_nroreg;
    // End of variables declaration//GEN-END:variables

}
