
package FORMULARIOS;

import BEANS.Periodo;
import BEANS.Reportes;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.Label;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;


public class frm_Historial extends javax.swing.JDialog {


    void cargar(){
    try{
    cbo_periodo.removeAllItems();
    Periodo per=new Periodo();
    ArrayList lista=new ArrayList();
    lista=per.listado_periodos();

    for(int i=0;i<lista.size();i++){
    per=(Periodo)lista.get(i);
    cbo_periodo.addItem(per.getId_codper() + " - " + per.getC_desper());
    }

    cbo_tipges.removeAllItems();
    cbo_tipges.addItem("01 - LLAMADA");
    cbo_tipges.addItem("02 - CARTA");
    cbo_tipges.addItem("03 - VISITA");    
    cbo_tipges.setSelectedItem("03 - VISITA");

    }catch(Exception ioE){
    JOptionPane.showMessageDialog(null, ioE);
    }

    }

    public frm_Historial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.cargar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbo_periodo = new javax.swing.JComboBox();
        cbo_tipges = new javax.swing.JComboBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_nroreg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte Historial");
        getContentPane().setLayout(null);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mostrar.JPG"))); // NOI18N
        jButton1.setText("Mostrar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.JPG"))); // NOI18N
        jButton2.setText("Exportar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 895, 50);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios de Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.blue)); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel1.setText("Periodo :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 60, 17);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel2.setText("Tip. Gestion :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(280, 30, 85, 17);

        cbo_periodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_periodo);
        cbo_periodo.setBounds(90, 27, 175, 22);

        cbo_tipges.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_tipges);
        cbo_tipges.setBounds(370, 27, 120, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 55, 880, 60);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(10, 120, 875, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "c_agencia", "c_territorio", "c_oficina", "c_nomsubpro", "c_contrato", "c_nombre", "c_divisa", "n_saldohoy", "n_diasvenc", "c_destcon", "c_destres", "f_fecresp", "c_dia01", "c_dia02", "c_dia03", "c_dia04", "c_dia05", "c_dia06", "c_dia07", "c_dia08", "c_dia09", "c_dia10", "c_dia11", "c_dia12", "c_dia13", "c_dia14", "c_dia15", "c_dia16", "c_dia17", "c_dia18", "c_dia19", "c_dia20", "c_dia21", "c_dia22", "c_dia23", "c_dia24", "c_dia25", "c_dia26", "c_dia27", "c_dia28", "c_dia29", "c_dia30", "c_dia31"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 875, 350);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel3.setText("Registros :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 7, 68, 17);

        lbl_nroreg.setEditable(false);
        lbl_nroreg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lbl_nroreg.setText("0");
        jPanel2.add(lbl_nroreg);
        lbl_nroreg.setBounds(105, 5, 60, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 517, 893, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{

      Reportes re=new Reportes();

      String id_codper=String.valueOf(cbo_periodo.getSelectedItem()).substring(0, 5);
      String id_codtges="";

      if(cbo_tipges.getSelectedItem()=="Todos"){
      id_codtges="";
      }else{
      id_codtges=String.valueOf(cbo_tipges.getSelectedItem()).substring(0, 2);
      }

      ResultSet rs=re.reporte_historial(id_codper, id_codtges);
      ResultSetMetaData rmdt=rs.getMetaData();


      int columnas=rmdt.getColumnCount();

      DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
      m.setRowCount(0);

       int num=0;
       while(rs.next()){

          Object fila[]={"","","","","","","","","","","","","","","","","","","","",
          "","","","","","","","","","","","","","","","","","","","","","",""};
           m.addRow(fila);
           for(int col=1;col<=columnas;col++){
           m.setValueAt(rs.getString(col), num, col-1);
           }jTable1.setModel(m);
           num++;
         
       }
       lbl_nroreg.setText(num + "");

     }catch(Exception ioE){
     JOptionPane.showMessageDialog(null, ioE);
     }
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      try{
        JFileChooser caja=new JFileChooser();
        caja.showSaveDialog(null);
        File arch=caja.getSelectedFile();

        if(arch==null){
        return;
        }

        DataOutputStream out=new DataOutputStream(new FileOutputStream(arch + ".xls"));
        WritableWorkbook w = Workbook.createWorkbook(out);
        WritableSheet s = w.createSheet("reporte", 0);
        WritableFont headersfont=new WritableFont(WritableFont.ARIAL, 10, WritableFont.BOLD, false, UnderlineStyle.NO_UNDERLINE, Colour.WHITE);
        WritableCellFormat headersformat=new WritableCellFormat(headersfont);
        headersformat.setBackground(Colour.ORANGE);
        
        s.addCell(new Label(0, 0, String.valueOf("c_agencia"),headersformat));
        s.addCell(new Label(1, 0, String.valueOf("c_territorio"),headersformat));
        s.addCell(new Label(2, 0, String.valueOf("c_oficina"),headersformat));
        s.addCell(new Label(3, 0, String.valueOf("c_nomsubpro"),headersformat));
        s.addCell(new Label(4, 0, String.valueOf("c_contrato"),headersformat));
        s.addCell(new Label(5, 0, String.valueOf("c_nombre"),headersformat));
        s.addCell(new Label(6, 0, String.valueOf("c_divisa"),headersformat));
        s.addCell(new Label(7, 0, String.valueOf("n_saldohoy"),headersformat));
        s.addCell(new Label(8, 0, String.valueOf("n_diasvenc"),headersformat));
        s.addCell(new Label(9, 0, String.valueOf("c_destcon"),headersformat));
        s.addCell(new Label(10, 0, String.valueOf("c_destres"),headersformat));
        s.addCell(new Label(11, 0, String.valueOf("f_fecresp_ult"),headersformat));
        s.addCell(new Label(12, 0, String.valueOf("c_dia01"),headersformat));
        s.addCell(new Label(13, 0, String.valueOf("c_dia02"),headersformat));
        s.addCell(new Label(14, 0, String.valueOf("c_dia03"),headersformat));
        s.addCell(new Label(15, 0, String.valueOf("c_dia04"),headersformat));
        s.addCell(new Label(16, 0, String.valueOf("c_dia05"),headersformat));
        s.addCell(new Label(17, 0, String.valueOf("c_dia06"),headersformat));
        s.addCell(new Label(18, 0, String.valueOf("c_dia07"),headersformat));
        s.addCell(new Label(19, 0, String.valueOf("c_dia08"),headersformat));
        s.addCell(new Label(20, 0, String.valueOf("c_dia09"),headersformat));
        s.addCell(new Label(21, 0, String.valueOf("c_dia10"),headersformat));
        s.addCell(new Label(22, 0, String.valueOf("c_dia11"),headersformat));
        s.addCell(new Label(23, 0, String.valueOf("c_dia12"),headersformat));
        s.addCell(new Label(24, 0, String.valueOf("c_dia13"),headersformat));
        s.addCell(new Label(25, 0, String.valueOf("c_dia14"),headersformat));
        s.addCell(new Label(26, 0, String.valueOf("c_dia15"),headersformat));
        s.addCell(new Label(27, 0, String.valueOf("c_dia16"),headersformat));
        s.addCell(new Label(28, 0, String.valueOf("c_dia17"),headersformat));
        s.addCell(new Label(29, 0, String.valueOf("c_dia18"),headersformat));

        s.addCell(new Label(30, 0, String.valueOf("c_dia19"),headersformat));
        s.addCell(new Label(31, 0, String.valueOf("c_dia20"),headersformat));
        s.addCell(new Label(32, 0, String.valueOf("c_dia21"),headersformat));
        s.addCell(new Label(33, 0, String.valueOf("c_dia22"),headersformat));
        s.addCell(new Label(34, 0, String.valueOf("c_dia23"),headersformat));
        s.addCell(new Label(35, 0, String.valueOf("c_dia24"),headersformat));
        s.addCell(new Label(36, 0, String.valueOf("c_dia25"),headersformat));
        s.addCell(new Label(37, 0, String.valueOf("c_dia26"),headersformat));
        s.addCell(new Label(38, 0, String.valueOf("c_dia27"),headersformat));
        s.addCell(new Label(39, 0, String.valueOf("c_dia28"),headersformat));
        s.addCell(new Label(40, 0, String.valueOf("c_dia29"),headersformat));
        s.addCell(new Label(41, 0, String.valueOf("c_dia30"),headersformat));
        s.addCell(new Label(42, 0, String.valueOf("c_dia31"),headersformat));

        for(int i=0;i<jTable1.getRowCount();i++){

            for(int j=0;j<jTable1.getColumnCount();j++){
               Object objeto=jTable1.getValueAt(i,j);
               if(objeto!=null){
                  if(j==8){
                    s.addCell(new jxl.write.Number(j, i+1, Integer.parseInt(objeto + "")));
                  }else{
                    s.addCell(new Label(j, i+1, String.valueOf(objeto)));
                  }
               }else{
                 s.addCell(new Label(j, i+1, ""));
               }
            }
          }

          w.write();
          w.close();
          out.close();

          JOptionPane.showMessageDialog(null,"Reporte Terminado");
       }catch(Exception ioE){
        JOptionPane.showMessageDialog(null, ioE);
       }
     
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_Historial dialog = new frm_Historial(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
                dialog.setSize(900, 580);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbo_periodo;
    private javax.swing.JComboBox cbo_tipges;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField lbl_nroreg;
    // End of variables declaration//GEN-END:variables

}
