
package FORMULARIOS;

import BEANS.Gestion;
import BEANS.Periodo;
import BEANS.Reportes;
import java.awt.Rectangle;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.*;
//import jxl.write.Label;
//import jxl.write.WritableCellFormat;
//import jxl.write.WritableFont;
//import jxl.write.WritableSheet;
//import jxl.write.WritableWorkbook;


public class frm_reporte_gestion extends javax.swing.JDialog {

     String tipo="";
    
    void cargar(){
    try{
    cbo_periodo.removeAllItems();
    Periodo per=new Periodo();    
    ArrayList lista=new ArrayList();    
    lista=per.listado_periodos();
    
    for(int i=0;i<lista.size();i++){
    per=(Periodo)lista.get(i);
    cbo_periodo.addItem(per.getId_codper() + " - " + per.getC_desper());
    }

    cbo_tipges.removeAllItems();
    cbo_tipges.addItem("01 - LLAMADA");
    cbo_tipges.addItem("02 - CARTA");
    cbo_tipges.addItem("03 - VISITA");
    cbo_tipges.addItem("Todos");
    cbo_tipges.setSelectedItem("Todos");

    cbo_tipcon.removeAllItems();
    cbo_tipcon.addItem("01 - Contacto Directo");
    cbo_tipcon.addItem("02 - Contacto Indirecto");
    cbo_tipcon.addItem("03 - No Contacto");
    cbo_tipcon.addItem("Todos"); 
    cbo_tipcon.setSelectedItem("Todos");
    
    }catch(Exception e){
    
    }    
    }

    public frm_reporte_gestion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();  
        this.cargar();
        ((javax.swing.JSpinner.DateEditor)dtpf_fecini.getEditor()).getTextField().setEditable(false);
        ((javax.swing.JSpinner.DateEditor)dtpf_fecfin.getEditor()).getTextField().setEditable(false);
        rbt_fproceso.setSelected(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbo_periodo = new javax.swing.JComboBox();
        rbt_fproceso = new javax.swing.JRadioButton();
        rbt_fasignacion = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        dtpf_fecini = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        dtpf_fecfin = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbo_tipges = new javax.swing.JComboBox();
        cbo_tipres = new javax.swing.JComboBox();
        cbo_tipcon = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        txt_numdoc = new javax.swing.JTextField();
        txt_nomcont = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        rbt_taxi = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_nroreg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte de Gestion");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios de Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.blue)); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel1.setText("Periodo :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(15, 30, 65, 17);

        cbo_periodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_periodo);
        cbo_periodo.setBounds(85, 28, 170, 22);

        buttonGroup1.add(rbt_fproceso);
        rbt_fproceso.setFont(new java.awt.Font("Ubuntu", 0, 14));
        rbt_fproceso.setText("Fecha de Proceso");
        jPanel1.add(rbt_fproceso);
        rbt_fproceso.setBounds(20, 120, 155, 24);

        buttonGroup1.add(rbt_fasignacion);
        rbt_fasignacion.setFont(new java.awt.Font("Ubuntu", 0, 14));
        rbt_fasignacion.setText("Fecha de Asignacion");
        jPanel1.add(rbt_fasignacion);
        rbt_fasignacion.setBounds(185, 120, 175, 24);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel2.setText("Desde :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(15, 83, 50, 17);

        dtpf_fecini.setModel(new javax.swing.SpinnerDateModel());
        dtpf_fecini.setEditor(new javax.swing.JSpinner.DateEditor(dtpf_fecini, "dd/MM/yyyy"));
        jPanel1.add(dtpf_fecini);
        dtpf_fecini.setBounds(75, 82, 100, 22);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel3.setText("Hasta :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(185, 83, 45, 17);

        dtpf_fecfin.setModel(new javax.swing.SpinnerDateModel());
        dtpf_fecfin.setEditor(new javax.swing.JSpinner.DateEditor(dtpf_fecfin, "dd/MM/yyyy"));
        jPanel1.add(dtpf_fecfin);
        dtpf_fecfin.setBounds(240, 82, 100, 22);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel4.setText("Gestion :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(272, 29, 65, 17);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel5.setText("Respuesta :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(275, 57, 80, 17);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel6.setText("Nombres :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 85, 70, 17);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel7.setText("Tipo contacto :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(482, 28, 100, 17);

        cbo_tipges.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_tipges);
        cbo_tipges.setBounds(340, 26, 130, 22);

        cbo_tipres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_tipres);
        cbo_tipres.setBounds(360, 55, 560, 22);

        cbo_tipcon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_tipcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_tipconActionPerformed(evt);
            }
        });
        jPanel1.add(cbo_tipcon);
        cbo_tipcon.setBounds(590, 26, 160, 22);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel8.setText("Nº Docu. :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(760, 28, 70, 17);
        jPanel1.add(txt_numdoc);
        txt_numdoc.setBounds(835, 26, 100, 22);
        jPanel1.add(txt_nomcont);
        txt_nomcont.setBounds(430, 83, 260, 22);

        jCheckBox1.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jCheckBox1.setText("Mostrar Solo ultima Gestion");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(700, 83, 220, 24);

        buttonGroup1.add(rbt_taxi);
        rbt_taxi.setFont(new java.awt.Font("Ubuntu", 0, 14));
        rbt_taxi.setText("Semanal mi taxi");
        rbt_taxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_taxiActionPerformed(evt);
            }
        });
        jPanel1.add(rbt_taxi);
        rbt_taxi.setBounds(370, 120, 126, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 55, 945, 160);

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "f_fproceso", "c_agencia", "c_gestor", "c_territorio", "c_oficina", "c_subprod", "c_nomsubpro", "c_contrato", "c_codcent", "c_tpersona", "c_nombre", "c_divisa", "n_saldohoy", "c_direccion", "c_telefono", "c_codpostal", "c_codestado", "c_codprov", "c_coddist", "f_fincumpli", "n_diasvenc", "c_ubigeo", "c_dpto", "c_distprov", "c_tramodia", "c_tipodoc", "c_nrodoc", "c_tipofono1", "c_prefijo1", "c_fono1", "c_extension1", "c_tipofono2", "c_prefijo2", "c_fono2", "c_extension2", "c_tipofono3", "c_prefijo3", "c_fono3", "c_extension3", "c_tipofono4", "c_prefijo4", "c_fono4", "c_extension4", "c_tipofono5", "c_prefijo5", "c_fono5", "c_extension5", "c_email", "c_provision", "c_tarrastre", "n_impprov", "n_deutotobli", "n_deutotclie", "c_dessubpro", "c_nombof", "c_clientevip", "c_sobreendeu", "c_provmayor", "c_scoriesp", "c_inclin", "c_msueldo1", "c_bajaph", "f_fecasig", "f_fecmod", "n_idxges", "id_codtges", "c_destges", "id_codtcon", "c_destcon", "id_codtres", "c_destres", "c_destres_sub", "f_fecresp", "f_fecrevi", "f_fecprog", "c_obsges", "c_nomusu", "n_impprom"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 250, 940, 320);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mostrar.JPG"))); // NOI18N
        jButton1.setText("Mostrar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.JPG"))); // NOI18N
        jButton2.setText("Exportar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 960, 50);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(10, 220, 940, 25);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel9.setText("Nº Registros :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(15, 7, 85, 17);

        lbl_nroreg.setEditable(false);
        lbl_nroreg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lbl_nroreg.setText("0");
        jPanel2.add(lbl_nroreg);
        lbl_nroreg.setBounds(105, 5, 60, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 587, 960, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_tipconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_tipconActionPerformed
        try{
        String id_codtcon="";
        if(cbo_tipcon.getSelectedItem()!="Todos"){
        id_codtcon=String.valueOf(cbo_tipcon.getSelectedItem()).substring(0, 2);
        }else{
        id_codtcon="";
        }

        cbo_tipres.removeAllItems();
        Gestion llm=new Gestion();
        ArrayList lista=new ArrayList();
        lista=llm.Respuesta_llam(id_codtcon);

        for(int i=0;i<lista.size();i++){
        llm=(Gestion)lista.get(i);
        cbo_tipres.addItem(llm.getId_codtres() + " - " + llm.getC_destres());
        }cbo_tipres.addItem("Todos");
        cbo_tipres.setSelectedItem("Todos");
        
        }catch(Exception ioE){

        }

    }//GEN-LAST:event_cbo_tipconActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
      try{         
      SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
      String c_tipo="";      
      Reportes re=new Reportes();
      ArrayList lista=new ArrayList();
      String b_flgult_ges;
      String f_fecini=sdf.format(dtpf_fecini.getValue()) + " 00:00:00.000";
      String f_fecfin=sdf.format(dtpf_fecfin.getValue()) + " 00:00:00.000";
      String id_codper=String.valueOf(cbo_periodo.getSelectedItem()).substring(0, 5);
      String id_codtges="";
      String id_codtcon="";

      if(cbo_tipges.getSelectedItem()=="Todos"){
      id_codtges="";
      }else{
      id_codtges=String.valueOf(cbo_tipges.getSelectedItem()).substring(0, 2);
      }

      if(cbo_tipcon.getSelectedItem()=="Todos"){
      id_codtcon="";
      }else{
      id_codtcon=String.valueOf(cbo_tipcon.getSelectedItem()).substring(0, 2);
      }
      String id_codtres="";
      if(cbo_tipres.getSelectedItem()=="Todos"){
      id_codtres="";
      }else{
      id_codtres=String.valueOf(cbo_tipres.getSelectedItem()).substring(0, 2);
      }
      String c_nrodoc=txt_numdoc.getText();
      String c_nombre=txt_nomcont.getText();
      if(jCheckBox1.isSelected()){
      b_flgult_ges="1";
      }else{
      b_flgult_ges="";
      }
     
      if(rbt_fproceso.isSelected()){
      c_tipo="1";
      }else{
      c_tipo="0";
      }


      DefaultTableModel m=(DefaultTableModel)jTable1.getModel();

      if(rbt_taxi.isSelected()){
        tipo="1";
        lista=re.reporte_gestion_mitaxi(f_fecini, f_fecfin, id_codper);
        lbl_nroreg.setText(lista.size() + "");        

        m.setColumnCount(0);
        m.addColumn("c_codcent");
        m.addColumn("c_nombof");
        m.addColumn("c_dessubpro");
        m.addColumn("c_contrato");
        m.addColumn("tc_codcent");
        m.addColumn("c_nombre");
        m.addColumn("c_divisa");
        m.addColumn("n_saldohoy");
        m.addColumn("n_diasvenc");
        m.addColumn("c_destcon_mgllm");
        m.addColumn("c_destres_mgllm");
        m.addColumn("f_fecresp_mgllm");
        m.addColumn("n_impprom_mgllm");
        m.addColumn("c_obsges_mgllm");
        m.addColumn("c_nomusu_mgllm");
        m.addColumn("c_desresp_mt_mgllm");
        m.addColumn("c_estcuen_mt_mgllm");
        m.addColumn("c_destcon_ugllm");
        m.addColumn("c_destres_ugllm");
        m.addColumn("f_fecresp_ugllm");
        m.addColumn("n_impprom_ugllm");
        m.addColumn("c_obsges_ugllm");
        m.addColumn("c_nomusu_ugllm");
        m.addColumn("c_desresp_mt_ugllm");
        m.addColumn("c_estcuen_mt_ugllm");
        m.addColumn("f_fecresp_mgcam");
        m.addColumn("n_impprom_mgcam");
        m.addColumn("c_obsges_mgcam");
        m.addColumn("c_nomges_mgcam");
        m.addColumn("c_desresp_mt_mgcam");
        m.addColumn("c_estcuen_mt_mgcam");
        m.setNumRows(lista.size());

        for(int i=0;i<lista.size();i++){
         re=(Reportes)lista.get(i);

         m.setValueAt(re.getC_codcent(), i, 0);
         m.setValueAt(re.getC_nombof(), i, 1);
         m.setValueAt(re.getC_dessubpro(), i, 2);
         m.setValueAt(re.getC_contrato(), i, 3);
         m.setValueAt(re.getTc_codcent(), i, 4);
         m.setValueAt(re.getC_nombre(), i, 5);     
         m.setValueAt(re.getC_divisa(), i, 6);
         m.setValueAt(re.getN_saldohoy(), i, 7);
         m.setValueAt(re.getN_diasvenc(), i, 8);
         m.setValueAt(re.getC_destcon_mgllm(), i, 9);
         m.setValueAt(re.getC_destres_mgllm(), i, 10);

         if(re.getF_fecresp_mgllm()!=null){
          m.setValueAt(String.valueOf(re.getF_fecresp_mgllm()).substring(8, 10) + "/" +
          String.valueOf(re.getF_fecresp_mgllm()).substring(5, 7) + "/" +
          String.valueOf(re.getF_fecresp_mgllm()).substring(0, 4), i, 11);
         }else{
          m.setValueAt(re.getF_fecresp_mgllm(), i, 11);
         }
         
         m.setValueAt(re.getN_impprom_mgllm(), i, 12);
         m.setValueAt(re.getC_obsges_mgllm(), i, 13);
         m.setValueAt(re.getC_nomusu_mgllm(), i, 14);
         m.setValueAt(re.getC_desresp_mt_mgllm(), i, 15);
         m.setValueAt(re.getC_estcuen_mt_mgllm(), i, 16);
         m.setValueAt(re.getC_destcon_ugllm(), i, 17);
         m.setValueAt(re.getC_destres_ugllm(), i, 18);

         if(re.getF_fecresp_ugllm()!=null){
          m.setValueAt(String.valueOf(re.getF_fecresp_ugllm()).substring(8, 10) + "/" +
          String.valueOf(re.getF_fecresp_ugllm()).substring(5, 7) + "/" +
          String.valueOf(re.getF_fecresp_ugllm()).substring(0, 4), i, 19);
         }else{
          m.setValueAt(re.getF_fecresp_ugllm(), i, 19);
         }
         
         m.setValueAt(re.getN_impprom_ugllm(), i, 20);
         m.setValueAt(re.getC_obsges_ugllm(), i, 21);
         m.setValueAt(re.getC_nomusu_ugllm(), i, 22);
         m.setValueAt(re.getC_desresp_mt_ugllm(), i, 23);
         m.setValueAt(re.getC_estcuen_mt_ugllm(), i, 24);

         if(re.getF_fecresp_mgcam()!=null){
          m.setValueAt(String.valueOf(re.getF_fecresp_mgcam()).substring(8, 10) + "/" +
          String.valueOf(re.getF_fecresp_mgcam()).substring(5, 7) + "/" +
          String.valueOf(re.getF_fecresp_mgcam()).substring(0, 4), i, 25);
         }else{
          m.setValueAt(re.getF_fecresp_mgcam(), i, 25);
         }
         
         m.setValueAt(re.getN_impprom_mgcam(), i, 26);
         m.setValueAt(re.getC_obsges_mgcam(), i, 27);
         m.setValueAt(re.getC_nomges_mgcam(), i, 28);
         m.setValueAt(re.getC_desresp_mt_mgcam(), i, 29);
         m.setValueAt(re.getC_estcuen_mt_mgcam(), i, 30);

        }jTable1.setModel(m);

      }else{
      tipo="2";
      lista=re.Reporte_gestion(c_tipo,f_fecini, f_fecfin, id_codper, id_codtges, id_codtcon, id_codtres, b_flgult_ges, c_nrodoc, c_nombre);
      lbl_nroreg.setText(lista.size() + "");
      m.setColumnCount(0);
      m.addColumn("f_fproceso");
      m.addColumn("c_agencia");
      m.addColumn("c_gestor");
      m.addColumn("c_territorio");
      m.addColumn("c_oficina");
      m.addColumn("c_subprod");
      m.addColumn("c_nomsubpro");
      m.addColumn("c_contrato");
      m.addColumn("c_codcent");
      m.addColumn("c_tpersona");
      m.addColumn("c_nombre");
      m.addColumn("c_divisa");
      m.addColumn("n_saldohoy");
      m.addColumn("c_direccion");
      m.addColumn("c_telefono");
      m.addColumn("c_codpostal");
      m.addColumn("c_codestado");
      m.addColumn("c_codprov");
      m.addColumn("c_coddist");
      m.addColumn("f_fincumpli");
      m.addColumn("n_diasvenc");
      m.addColumn("c_ubigeo");
      m.addColumn("c_dpto");
      m.addColumn("c_distprov");
      m.addColumn("c_tramodia");
      m.addColumn("c_tipodoc");
      m.addColumn("c_nrodoc");
      m.addColumn("c_tipofono1");
      m.addColumn("c_prefijo1");
      m.addColumn("c_fono1");
      m.addColumn("c_extension1");
      m.addColumn("c_tipofono2");
      m.addColumn("c_prefijo2");
      m.addColumn("c_fono2");
      m.addColumn("c_extension2");
      m.addColumn("c_tipofono3");
      m.addColumn("c_prefijo3");
      m.addColumn("c_fono3");
      m.addColumn("c_extension3");
      m.addColumn("c_tipofono4");
      m.addColumn("c_prefijo4");
      m.addColumn("c_fono4");
      m.addColumn("c_extension4");
      m.addColumn("c_tipofono5");
      m.addColumn("c_prefijo5");
      m.addColumn("c_fono5");
      m.addColumn("c_extension5");
      m.addColumn("c_email");
      m.addColumn("c_provision");
      m.addColumn("c_tarrastre");
      m.addColumn("n_impprov");
      m.addColumn("n_deutotobli");
      m.addColumn("n_deutotclie");
      m.addColumn("c_dessubpro");
      m.addColumn("c_nombof");
      m.addColumn("c_clientevip");
      m.addColumn("c_sobreendeu");
      m.addColumn("c_provmayor");
      m.addColumn("c_scoriesp");
      m.addColumn("c_inclin");
      m.addColumn("c_msueldo1");
      m.addColumn("c_bajaph");
      m.addColumn("f_fecasig");
      m.addColumn("f_fecmod");
      m.addColumn("n_idxges");
      m.addColumn("id_codtges");
      m.addColumn("c_destges");
      m.addColumn("id_codtcon");
      m.addColumn("c_destcon");
      m.addColumn("id_codtres");
      m.addColumn("c_destres");
      m.addColumn("c_destres_sub");
      m.addColumn("f_fecresp");
      m.addColumn("f_fecrevi");
      m.addColumn("f_fecprog");
      m.addColumn("c_obsges");
      m.addColumn("c_nomusu");
      m.addColumn("n_impprom");
      m.setNumRows(lista.size());

      for(int i=0;i<lista.size();i++){
       re=(Reportes)lista.get(i);

       m.setValueAt(String.valueOf(re.getF_fproceso()).substring(8, 10) + "/" +
       String.valueOf(re.getF_fproceso()).substring(5, 7) + "/" + 
       String.valueOf(re.getF_fproceso()).substring(0, 4), i, 0);

       m.setValueAt(re.getC_agencia(), i, 1);
       m.setValueAt(re.getC_gestor(), i, 2);
       m.setValueAt(re.getC_territorio(), i, 3);
       m.setValueAt(re.getC_oficina(), i, 4);
       m.setValueAt(re.getC_subprod(), i, 5);
       m.setValueAt(re.getC_nomsubpro(), i, 6);
       m.setValueAt(re.getC_contrato(), i, 7);
       m.setValueAt(re.getC_codcent(), i, 8);
       m.setValueAt(re.getC_tpersona(), i, 9);
       m.setValueAt(re.getC_nombre(), i, 10);
       m.setValueAt(re.getC_divisa(), i, 11);
       m.setValueAt(re.getN_saldohoy(), i, 12);
       m.setValueAt(re.getC_direccion(), i, 13);
       m.setValueAt(re.getC_telefono(), i, 14);
       m.setValueAt(re.getC_codpostal(), i, 15);
       m.setValueAt(re.getC_codestado(), i, 16);
       m.setValueAt(re.getC_codprov(), i, 17);
       m.setValueAt(re.getC_coddist(), i, 18);

       if(re.getF_fincumpli()!=null){
         m.setValueAt(String.valueOf(re.getF_fincumpli()).substring(8, 10) + "/" +
         String.valueOf(re.getF_fincumpli()).substring(5, 7) + "/" +
         String.valueOf(re.getF_fincumpli()).substring(0, 4), i, 19);
       }else{
         m.setValueAt(re.getF_fincumpli(), i, 19);
       }
       
       m.setValueAt(re.getN_diasvenc(), i, 20);
       m.setValueAt(re.getC_ubigeo(), i, 21);
       m.setValueAt(re.getC_dpto(), i, 22);
       m.setValueAt(re.getC_distprov(), i, 23);
       m.setValueAt(re.getC_tramodia(), i, 24);
       m.setValueAt(re.getC_tipodoc(), i, 25);
       m.setValueAt(re.getC_nrodoc(), i, 26);
       m.setValueAt(re.getC_tipofono1(), i, 27);
       m.setValueAt(re.getC_prefijo1(), i, 28);
       m.setValueAt(re.getC_fono1(), i, 29);
       m.setValueAt(re.getC_extension1(), i, 30);
       m.setValueAt(re.getC_tipofono2(), i, 31);
       m.setValueAt(re.getC_prefijo2(), i, 32);
       m.setValueAt(re.getC_fono2(), i, 33);
       m.setValueAt(re.getC_extension2(), i, 34);
       m.setValueAt(re.getC_tipofono3(), i, 35);
       m.setValueAt(re.getC_prefijo3(), i, 36);
       m.setValueAt(re.getC_fono3(), i, 37);
       m.setValueAt(re.getC_extension3(), i, 38);
       m.setValueAt(re.getC_tipofono4(), i, 39);
       m.setValueAt(re.getC_prefijo4(), i, 40);
       m.setValueAt(re.getC_fono4(), i, 41);
       m.setValueAt(re.getC_extension4(), i, 42);
       m.setValueAt(re.getC_tipofono5(), i, 43);
       m.setValueAt(re.getC_prefijo5(), i, 44);
       m.setValueAt(re.getC_fono5(), i, 45);
       m.setValueAt(re.getC_extension5(), i, 46);
       m.setValueAt(re.getC_email(), i, 47);
       m.setValueAt(re.getC_provision(), i, 48);
       m.setValueAt(re.getC_tarrastre(), i, 49);
       m.setValueAt(re.getN_impprov(), i, 50);
       m.setValueAt(re.getN_deutotobli(), i, 51);
       m.setValueAt(re.getN_deutotclie(), i, 52);
       m.setValueAt(re.getC_dessubpro(), i, 53);
       m.setValueAt(re.getC_nombof(), i, 54);
       m.setValueAt(re.getC_clientevip(), i, 55);
       m.setValueAt(re.getC_sobreendeu(), i, 56);
       m.setValueAt(re.getC_provmayor(), i, 57);
       m.setValueAt(re.getC_scoriesp(), i, 58);
       m.setValueAt(re.getC_inclin(), i, 59);
       m.setValueAt(re.getC_msueldo1(), i, 60);
       m.setValueAt(re.getC_bajaph(), i, 61);

       m.setValueAt(String.valueOf(re.getF_fecasig()).substring(8, 10) + "/" +
       String.valueOf(re.getF_fecasig()).substring(5, 7) + "/" +
       String.valueOf(re.getF_fecasig()).substring(0, 4), i, 62);

       if(re.getF_fecmod()!=null){
         m.setValueAt(String.valueOf(re.getF_fecmod()).substring(8, 10) + "/" +
         String.valueOf(re.getF_fecmod()).substring(5, 7) + "/" +
         String.valueOf(re.getF_fecmod()).substring(0, 4) +
         String.valueOf(re.getF_fecmod()).substring(10, 19), i, 63);
       }else{
         m.setValueAt(re.getF_fecmod(), i, 63);
       }
       
       m.setValueAt(re.getN_idxges(), i, 64);
       m.setValueAt(re.getId_codtges(), i, 65);
       m.setValueAt(re.getC_destges(), i, 66);
       m.setValueAt(re.getId_codtcon(), i, 67);
       m.setValueAt(re.getC_destcon(), i, 68);
       m.setValueAt(re.getId_codtres(), i, 69);
       m.setValueAt(re.getC_destres(), i, 70);
       m.setValueAt(re.getC_destres_sub(), i, 71);

       if(re.getF_fecresp()!=null){
        m.setValueAt(String.valueOf(re.getF_fecresp()).substring(8, 10) + "/" +
        String.valueOf(re.getF_fecresp()).substring(5, 7) + "/" +
        String.valueOf(re.getF_fecresp()).substring(0, 4), i, 72);
       }else{
        m.setValueAt(re.getF_fecresp(), i, 72);
       }

       if(re.getF_fecrevi()!=null){
        m.setValueAt(String.valueOf(re.getF_fecrevi()).substring(8, 10) + "/" +
        String.valueOf(re.getF_fecrevi()).substring(5, 7) + "/" +
        String.valueOf(re.getF_fecrevi()).substring(0, 4) , i, 73);
       }else{
        m.setValueAt(re.getF_fecrevi(), i, 73);
       }
       
       if(re.getF_fecprog()!=null){
        m.setValueAt(String.valueOf(re.getF_fecprog()).substring(8, 10) + "/" +
        String.valueOf(re.getF_fecprog()).substring(5, 7) + "/" +
        String.valueOf(re.getF_fecprog()).substring(0, 4) , i, 74);
       }else{
        m.setValueAt(re.getF_fecprog(), i, 74);
       }

       
       m.setValueAt(re.getC_obsges(), i, 75);
       m.setValueAt(re.getC_nomusu(), i, 76);
       m.setValueAt(re.getN_impprom(), i, 77);

      }this.jTable1.setModel(m);
      
      }
     }catch(Exception ioE){
     JOptionPane.showMessageDialog(null, ioE);
     }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try{
        JFileChooser caja=new JFileChooser();
        caja.showSaveDialog(null);
        File arch=caja.getSelectedFile();

        if(arch==null){
        return;
        }

         DataOutputStream out=new DataOutputStream(new FileOutputStream(arch + ".xls"));
         WritableWorkbook w = Workbook.createWorkbook(out);
         WritableSheet s = w.createSheet("reporte", 0);
         WritableFont headersfont=new WritableFont(WritableFont.ARIAL, 10, WritableFont.BOLD, false, UnderlineStyle.NO_UNDERLINE, Colour.WHITE);
         WritableCellFormat headersformat=new WritableCellFormat(headersfont);
         headersformat.setBackground(Colour.ORANGE);

        if(tipo.equals("1")){     

           s.addCell(new Label(0, 0, String.valueOf("c_codcent"),headersformat));
           s.addCell(new Label(1, 0, String.valueOf("c_nombof"),headersformat));
           s.addCell(new Label(2, 0, String.valueOf("c_dessubpro"),headersformat));
           s.addCell(new Label(3, 0, String.valueOf("c_contrato"),headersformat));
           s.addCell(new Label(4, 0, String.valueOf("tc_codcent"),headersformat));
           s.addCell(new Label(5, 0, String.valueOf("c_nombre"),headersformat));
           s.addCell(new Label(6, 0, String.valueOf("c_divisa"),headersformat));
           s.addCell(new Label(7, 0, String.valueOf("n_saldohoy"),headersformat));
           s.addCell(new Label(8, 0, String.valueOf("n_diasvenc"),headersformat));
           s.addCell(new Label(9, 0, String.valueOf("c_destcon_mgllm"),headersformat));
           s.addCell(new Label(10, 0, String.valueOf("c_destres_mgllm"),headersformat));
           s.addCell(new Label(11, 0, String.valueOf("f_fecresp_mgllm"),headersformat));
           s.addCell(new Label(12, 0, String.valueOf("n_impprom_mgllm"),headersformat));
           s.addCell(new Label(13, 0, String.valueOf("c_obsges_mgllm"),headersformat));
           s.addCell(new Label(14, 0, String.valueOf("c_nomusu_mgllm"),headersformat));
           s.addCell(new Label(15, 0, String.valueOf("c_desresp_mt_mgllm"),headersformat));
           s.addCell(new Label(16, 0, String.valueOf("c_estcuen_mt_mgllm"),headersformat));
           s.addCell(new Label(17, 0, String.valueOf("c_destcon_ugllm"),headersformat));
           s.addCell(new Label(18, 0, String.valueOf("c_destres_ugllm"),headersformat));
           s.addCell(new Label(19, 0, String.valueOf("f_fecresp_ugllm"),headersformat));
           s.addCell(new Label(20, 0, String.valueOf("n_impprom_ugllm"),headersformat));
           s.addCell(new Label(21, 0, String.valueOf("c_obsges_ugllm"),headersformat));
           s.addCell(new Label(22, 0, String.valueOf("c_nomusu_ugllm"),headersformat));
           s.addCell(new Label(23, 0, String.valueOf("c_desresp_mt_ugllm"),headersformat));
           s.addCell(new Label(24, 0, String.valueOf("c_estcuen_mt_ugllm"),headersformat));
           s.addCell(new Label(25, 0, String.valueOf("f_fecresp_mgcam"),headersformat));
           s.addCell(new Label(26, 0, String.valueOf("n_impprom_mgcam"),headersformat));
           s.addCell(new Label(27, 0, String.valueOf("c_obsges_mgcam"),headersformat));
           s.addCell(new Label(28, 0, String.valueOf("c_nomges_mgcam"),headersformat));
           s.addCell(new Label(29, 0, String.valueOf("c_desresp_mt_mgcam"),headersformat));
           s.addCell(new Label(30, 0, String.valueOf("c_estcuen_mt_mgcam"),headersformat));


          for(int i=0;i<jTable1.getRowCount();i++){
             for(int j=0;j<jTable1.getColumnCount();j++){
               Object objeto=jTable1.getValueAt(i,j);
               if(objeto!=null){
                  if(j==8){
                    s.addCell(new jxl.write.Number(j, i+1, Integer.parseInt(objeto + "")));
                  }else{
                    s.addCell(new Label(j, i+1, String.valueOf(objeto)));
                  }
               }else{
                s.addCell(new Label(j, i+1, ""));
               }
             }
          }

          w.write();
          w.close();
          out.close();

        }else{
           s.addCell(new Label(0, 0, String.valueOf("f_fproceso"),headersformat));
           s.addCell(new Label(1, 0, String.valueOf("c_agencia"),headersformat));
           s.addCell(new Label(2, 0, String.valueOf("c_gestor"),headersformat));
           s.addCell(new Label(3, 0, String.valueOf("c_territorio"),headersformat));
           s.addCell(new Label(4, 0, String.valueOf("c_oficina"),headersformat));
           s.addCell(new Label(5, 0, String.valueOf("c_subprod"),headersformat));
           s.addCell(new Label(6, 0, String.valueOf("c_nomsubpro"),headersformat));
           s.addCell(new Label(7, 0, String.valueOf("c_contrato"),headersformat));
           s.addCell(new Label(8, 0, String.valueOf("c_codcent"),headersformat));
           s.addCell(new Label(9, 0, String.valueOf("c_tpersona"),headersformat));
           s.addCell(new Label(10, 0, String.valueOf("c_nombre"),headersformat));
           s.addCell(new Label(11, 0, String.valueOf("c_divisa"),headersformat));
           s.addCell(new Label(12, 0, String.valueOf("n_saldohoy"),headersformat));
           s.addCell(new Label(13, 0, String.valueOf("c_direccion"),headersformat));

           s.addCell(new Label(14, 0, String.valueOf("c_telefono"),headersformat));
           s.addCell(new Label(15, 0, String.valueOf("c_codpostal"),headersformat));
           s.addCell(new Label(16, 0, String.valueOf("c_codestado"),headersformat));
           s.addCell(new Label(17, 0, String.valueOf("c_codprov"),headersformat));
           s.addCell(new Label(18, 0, String.valueOf("c_coddist"),headersformat));
           s.addCell(new Label(19, 0, String.valueOf("f_fincumpli"),headersformat));
           s.addCell(new Label(20, 0, String.valueOf("n_diasvenc"),headersformat));
           s.addCell(new Label(21, 0, String.valueOf("c_ubigeo"),headersformat));
           s.addCell(new Label(22, 0, String.valueOf("c_dpto"),headersformat));

           s.addCell(new Label(23, 0, String.valueOf("c_distprov"),headersformat));
           s.addCell(new Label(24, 0, String.valueOf("c_tramodia"),headersformat));
           s.addCell(new Label(25, 0, String.valueOf("c_tipodoc"),headersformat));
           s.addCell(new Label(26, 0, String.valueOf("c_nrodoc"),headersformat));
           s.addCell(new Label(27, 0, String.valueOf("c_tipofono1"),headersformat));
           s.addCell(new Label(28, 0, String.valueOf("c_prefijo1"),headersformat));
           s.addCell(new Label(29, 0, String.valueOf("c_fono1"),headersformat));
           s.addCell(new Label(30, 0, String.valueOf("c_extension1"),headersformat));
           s.addCell(new Label(31, 0, String.valueOf("c_tipofono2"),headersformat));
           s.addCell(new Label(32, 0, String.valueOf("c_prefijo2"),headersformat));
           s.addCell(new Label(33, 0, String.valueOf("c_fono2"),headersformat));
           s.addCell(new Label(34, 0, String.valueOf("c_extension2"),headersformat));
           s.addCell(new Label(35, 0, String.valueOf("c_tipofono3"),headersformat));
           s.addCell(new Label(36, 0, String.valueOf("c_prefijo3"),headersformat));
           s.addCell(new Label(37, 0, String.valueOf("c_fono3"),headersformat));
           s.addCell(new Label(38, 0, String.valueOf("c_extension3"),headersformat));

           s.addCell(new Label(39, 0, String.valueOf("c_tipofono4"),headersformat));
           s.addCell(new Label(40, 0, String.valueOf("c_prefijo4"),headersformat));
           s.addCell(new Label(41, 0, String.valueOf("c_fono4"),headersformat));
           s.addCell(new Label(42, 0, String.valueOf("c_extension4"),headersformat));
           s.addCell(new Label(43, 0, String.valueOf("c_tipofono5"),headersformat));
           s.addCell(new Label(44, 0, String.valueOf("c_prefijo5"),headersformat));
           s.addCell(new Label(45, 0, String.valueOf("c_fono5"),headersformat));
           s.addCell(new Label(46, 0, String.valueOf("c_extension5"),headersformat));
           s.addCell(new Label(47, 0, String.valueOf("c_email"),headersformat));

           s.addCell(new Label(48, 0, String.valueOf("c_provision"),headersformat));
           s.addCell(new Label(49, 0, String.valueOf("c_tarrastre"),headersformat));
           s.addCell(new Label(50, 0, String.valueOf("n_impprov"),headersformat));
           s.addCell(new Label(51, 0, String.valueOf("n_deutotobli"),headersformat));
           s.addCell(new Label(52, 0, String.valueOf("n_deutotclie"),headersformat));
           s.addCell(new Label(53, 0, String.valueOf("c_dessubpro"),headersformat));
           s.addCell(new Label(54, 0, String.valueOf("c_nombof"),headersformat));
           s.addCell(new Label(55, 0, String.valueOf("c_clientevip"),headersformat));
           s.addCell(new Label(56, 0, String.valueOf("c_sobreendeu"),headersformat));

           s.addCell(new Label(57, 0, String.valueOf("c_provmayor"),headersformat));
           s.addCell(new Label(58, 0, String.valueOf("c_scoriesp"),headersformat));
           s.addCell(new Label(59, 0, String.valueOf("c_inclin"),headersformat));
           s.addCell(new Label(60, 0, String.valueOf("c_msueldo1"),headersformat));
           s.addCell(new Label(61, 0, String.valueOf("c_bajaph"),headersformat));
           s.addCell(new Label(62, 0, String.valueOf("f_fecasig"),headersformat));
           s.addCell(new Label(63, 0, String.valueOf("f_fecmod"),headersformat));
           s.addCell(new Label(64, 0, String.valueOf("n_idxges"),headersformat));

           s.addCell(new Label(65, 0, String.valueOf("id_codtges"),headersformat));
           s.addCell(new Label(66, 0, String.valueOf("c_destges"),headersformat));
           s.addCell(new Label(67, 0, String.valueOf("id_codtcon"),headersformat));
           s.addCell(new Label(68, 0, String.valueOf("c_destcon"),headersformat));
           s.addCell(new Label(69, 0, String.valueOf("id_codtres"),headersformat));
           s.addCell(new Label(70, 0, String.valueOf("c_destres"),headersformat));
           s.addCell(new Label(71, 0, String.valueOf("c_destres_sub"),headersformat));
           s.addCell(new Label(72, 0, String.valueOf("f_fecresp"),headersformat));
           s.addCell(new Label(73, 0, String.valueOf("f_fecrevi"),headersformat));
           s.addCell(new Label(74, 0, String.valueOf("f_fecprog"),headersformat));
           s.addCell(new Label(75, 0, String.valueOf("c_obsges"),headersformat));
           s.addCell(new Label(76, 0, String.valueOf("c_nomusu"),headersformat));
           s.addCell(new Label(77, 0, String.valueOf("n_impprom"),headersformat));

      
          for(int i=0;i<jTable1.getRowCount();i++){
              for(int j=0;j<jTable1.getColumnCount();j++){
                Object objeto=jTable1.getValueAt(i,j);
                 if(objeto!=null){
                   if(j==20 || j==64){
                     s.addCell(new jxl.write.Number(j, i+1, Integer.parseInt(objeto + "")));
                     }else{
                     s.addCell(new Label(j, i+1, String.valueOf(objeto)));
                   }
                 }else{
                   s.addCell(new Label(j, i+1, ""));
                 }
              }
          }

          w.write();
          w.close();
          out.close();         

        }JOptionPane.showMessageDialog(null,"Reporte Terminado");
        }catch(Exception ioE){
        JOptionPane.showMessageDialog(null, ioE);
       }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
      evt.consume();
    }//GEN-LAST:event_jTable1KeyPressed

    private void rbt_taxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_taxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbt_taxiActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_reporte_gestion dialog = new frm_reporte_gestion(new javax.swing.JFrame(), true);
                dialog.setSize(967,650);
                dialog.setVisible(true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbo_periodo;
    private javax.swing.JComboBox cbo_tipcon;
    private javax.swing.JComboBox cbo_tipges;
    private javax.swing.JComboBox cbo_tipres;
    private javax.swing.JSpinner dtpf_fecfin;
    private javax.swing.JSpinner dtpf_fecini;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField lbl_nroreg;
    private javax.swing.JRadioButton rbt_fasignacion;
    private javax.swing.JRadioButton rbt_fproceso;
    private javax.swing.JRadioButton rbt_taxi;
    private javax.swing.JTextField txt_nomcont;
    private javax.swing.JTextField txt_numdoc;
    // End of variables declaration//GEN-END:variables

}
