
package FORMULARIOS;

import BEANS.Cartera;
import BEANS.Gestion;
import BEANS.Globales;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Sheet;
import jxl.Workbook;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.Label;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

public class frm_impresion_carta extends javax.swing.JDialog {

      File arch;

      void cargar(){
      try{
      cbo_distrito.removeAllItems();
      Cartera car=new Cartera();
      ArrayList lista=new ArrayList();
      lista=car.datos_distprov();
      for(int i=0;i<lista.size();i++){
      car=(Cartera)lista.get(i);
      cbo_distrito.addItem(car.getC_distprov());
      }cbo_distrito.addItem("Todos");
      cbo_distrito.setSelectedItem("Todos");

      cbo_tipcon.removeAllItems();
      cbo_tipcon.addItem("01 - Contacto Directo");
      cbo_tipcon.addItem("02 - Contacto Indirecto");
      cbo_tipcon.addItem("03 - No Contacto");
      cbo_tipcon.addItem("Todos");
      cbo_tipcon.setSelectedItem("Todos");
      }catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
      }
      }

    public frm_impresion_carta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ((javax.swing.JSpinner.DateEditor)dtpf_fecpro.getEditor()).getTextField().setEditable(false);
        this.cargar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_mostrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lbl_ruta = new javax.swing.JTextPane();
        lbln_regcar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cbo_tipcon = new javax.swing.JComboBox();
        cbo_distrito = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtc_nomcont = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dtpf_fecpro = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        txtc_numdoc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbo_tipres = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        lbl_nroreg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Impresion de Cartas");
        getContentPane().setLayout(null);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mostrar.JPG"))); // NOI18N
        btn_mostrar.setText("Mostrar");
        btn_mostrar.setFocusable(false);
        btn_mostrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mostrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_mostrar);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print.JPG"))); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.JPG"))); // NOI18N
        jButton3.setText("Exportar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 930, 44);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setBackground(new java.awt.Color(255, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "f_fproceso", "c_codcent", "c_contrato", "c_tipodoc", "c_nrodoc", "c_nombre", "c_nomsubpro_car", "c_nomsubpro", "c_dessubpro", "c_divisa_car", "c_divisa", "n_saldohoy", "n_diasvenc", "c_flgdir", "c_dirimp", "c_disimp", "f_fproceso_ges", "f_fecimp", "c_desrspta", "c_desrspta_sub", "f_fecasig_ult", "id_codtcon", "c_destcon", "id_codtres", "c_destres"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(87);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(90);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(160);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTable2.getColumnModel().getColumn(5).setPreferredWidth(270);
        jTable2.getColumnModel().getColumn(6).setPreferredWidth(130);
        jTable2.getColumnModel().getColumn(7).setPreferredWidth(120);
        jTable2.getColumnModel().getColumn(8).setPreferredWidth(130);
        jTable2.getColumnModel().getColumn(9).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(10).setPreferredWidth(70);
        jTable2.getColumnModel().getColumn(11).setPreferredWidth(90);
        jTable2.getColumnModel().getColumn(12).setPreferredWidth(90);
        jTable2.getColumnModel().getColumn(13).setPreferredWidth(90);
        jTable2.getColumnModel().getColumn(14).setPreferredWidth(300);
        jTable2.getColumnModel().getColumn(15).setPreferredWidth(120);
        jTable2.getColumnModel().getColumn(16).setPreferredWidth(87);
        jTable2.getColumnModel().getColumn(17).setPreferredWidth(87);
        jTable2.getColumnModel().getColumn(18).setPreferredWidth(130);
        jTable2.getColumnModel().getColumn(19).setPreferredWidth(130);
        jTable2.getColumnModel().getColumn(20).setPreferredWidth(87);
        jTable2.getColumnModel().getColumn(21).setPreferredWidth(90);
        jTable2.getColumnModel().getColumn(22).setPreferredWidth(140);
        jTable2.getColumnModel().getColumn(23).setPreferredWidth(90);
        jTable2.getColumnModel().getColumn(24).setPreferredWidth(320);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 250, 900, 360);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios de Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.blue)); // NOI18N
        jPanel1.setLayout(null);

        jScrollPane3.setViewportView(jList2);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 110, 110);

        jButton6.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jButton6.setText("Seleccionar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(125, 15, 107, 29);

        lbl_ruta.setBackground(java.awt.Color.white);
        jScrollPane4.setViewportView(lbl_ruta);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(128, 50, 310, 50);

        lbln_regcar.setEditable(false);
        lbln_regcar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbln_regcar.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        lbln_regcar.setText("0");
        jPanel1.add(lbln_regcar);
        lbln_regcar.setBounds(130, 110, 55, 22);

        jLabel1.setText("Registros Cargados");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 113, 140, 18);

        jButton7.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jButton7.setText("Añadir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(235, 15, 100, 29);

        jButton8.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jButton8.setText("Limpiar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(340, 15, 100, 29);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel11.setText("T.Contacto :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(460, 110, 82, 17);

        cbo_tipcon.setFont(new java.awt.Font("Ubuntu", 0, 14));
        cbo_tipcon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_tipcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_tipconActionPerformed(evt);
            }
        });
        jPanel1.add(cbo_tipcon);
        cbo_tipcon.setBounds(600, 110, 180, 22);

        cbo_distrito.setFont(new java.awt.Font("Ubuntu", 0, 14));
        cbo_distrito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_distrito);
        cbo_distrito.setBounds(600, 82, 230, 22);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel9.setText("Distrito Prov :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 85, 90, 17);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel8.setText("Apellidos Nombres :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(460, 55, 130, 17);
        jPanel1.add(txtc_nomcont);
        txtc_nomcont.setBounds(600, 54, 260, 22);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel2.setText("F. Proceso :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 21, 75, 17);

        dtpf_fecpro.setFont(new java.awt.Font("Ubuntu", 0, 14));
        dtpf_fecpro.setModel(new javax.swing.SpinnerDateModel());
        dtpf_fecpro.setEditor(new javax.swing.JSpinner.DateEditor(dtpf_fecpro, "dd/MM/yyyy"));
        jPanel1.add(dtpf_fecpro);
        dtpf_fecpro.setBounds(540, 20, 100, 22);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel7.setText("Nº Docu :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(655, 21, 60, 17);

        txtc_numdoc.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jPanel1.add(txtc_numdoc);
        txtc_numdoc.setBounds(725, 20, 90, 22);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel4.setText("T.Respuesta :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(345, 140, 90, 17);

        cbo_tipres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_tipres);
        cbo_tipres.setBounds(440, 138, 450, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 50, 900, 180);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel3.setText("N° Registros :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 620, 84, 17);

        lbl_nroreg.setBackground(java.awt.Color.white);
        lbl_nroreg.setEditable(false);
        lbl_nroreg.setFont(new java.awt.Font("Ubuntu", 0, 14));
        lbl_nroreg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lbl_nroreg.setText("0");
        getContentPane().add(lbl_nroreg);
        lbl_nroreg.setBounds(118, 620, 60, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        try{
            Globales glo=new Globales();
            Cartera car=new Cartera();
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String f_fproceso, id_codper, c_nrodoc,c_nombre,c_distprov, 
            id_codtcon, id_codtres;
            String pc_nrodoc_secuencia="";
            

            f_fproceso=sdf.format(dtpf_fecpro.getValue()) + " 00:00:00.000";
            id_codper=glo.getId_codper();
            c_nrodoc=txtc_numdoc.getText();
            c_nombre=txtc_nomcont.getText();
          

            if(cbo_tipcon.getSelectedItem()!= "Todos"){
             id_codtcon = String.valueOf(cbo_tipcon.getSelectedItem()).substring(0, 2);
            }else{
             id_codtcon="";
            }

            if(cbo_tipres.getSelectedItem()!= "Todos"){
               id_codtres = String.valueOf(cbo_tipres.getSelectedItem()).substring(0, 4).trim();
            }else{
             id_codtres="";
            }

            if(cbo_distrito.getSelectedItem()!="Todos"){
              c_distprov = String.valueOf(cbo_distrito.getSelectedItem());
            }else{
              c_distprov = "";
            }


            if(Integer.parseInt(lbln_regcar.getText()) > 0){             
            for(int i= 0; i<Integer.parseInt(lbln_regcar.getText());i++){
            jList2.setSelectedIndex(i);
            pc_nrodoc_secuencia = pc_nrodoc_secuencia + jList2.getSelectedValue() + ",";
            }
            }

            ArrayList lista=new ArrayList();
            lista=car.lista_impresion_cartas(id_codper, f_fproceso,
            c_nrodoc, c_nombre, c_distprov, id_codtcon,
            id_codtres, pc_nrodoc_secuencia);
       
            lbl_nroreg.setText(lista.size() + "");
            
            DefaultTableModel m=(DefaultTableModel)jTable2.getModel();
            m.setNumRows(lista.size());
            for(int i=0;i<lista.size();i++){
            car=(Cartera)lista.get(i);

            m.setValueAt(String.valueOf(car.getF_fproceso()).substring(8, 10) + "/" +
            String.valueOf(car.getF_fproceso()).substring(5, 7) + "/" + 
            String.valueOf(car.getF_fproceso()).substring(0, 4), i, 0);

            m.setValueAt(car.getC_codcent(), i, 1);
            m.setValueAt(car.getC_contrato(), i, 2);
            m.setValueAt(car.getC_tipodoc(), i, 3);
            m.setValueAt(car.getC_nrodoc(), i, 4);
            m.setValueAt(car.getC_nombre(), i, 5);
            m.setValueAt(car.getC_nomsubpro_car(), i, 6);
            m.setValueAt(car.getC_nomsubpro(), i, 7);
            m.setValueAt(car.getC_dessubpro(), i, 8);
            m.setValueAt(car.getC_divisa_car(), i, 9);
            m.setValueAt(car.getC_divisa(), i, 10);
            m.setValueAt(car.getN_saldohoy(), i, 11);
            m.setValueAt(car.getN_diasvenc(), i, 12);
            m.setValueAt(car.getC_flgdir(), i, 13);
            m.setValueAt(car.getC_dirimp(), i, 14);
            m.setValueAt(car.getC_disimp(), i, 15);

            if(String.valueOf(car.getF_fproceso_ges()).trim().length()>4){
             m.setValueAt(String.valueOf(car.getF_fproceso_ges()).substring(8, 10) + "/" +
             String.valueOf(car.getF_fproceso_ges()).substring(5, 7) + "/" +
             String.valueOf(car.getF_fproceso_ges()).substring(0, 4), i, 16);
            }else{
             m.setValueAt(car.getF_fproceso_ges(), i, 16);
            }

            if(String.valueOf(car.getF_fecimp()).trim().length()>4){
             m.setValueAt(String.valueOf(car.getF_fecimp()).substring(8, 10) + "/" +
             String.valueOf(car.getF_fecimp()).substring(5, 7) + "/" +
             String.valueOf(car.getF_fecimp()).substring(0, 4), i, 17);
            }else{
             m.setValueAt(car.getF_fecimp(), i, 17);
            }

            m.setValueAt(car.getC_desrspta(), i, 18);
            m.setValueAt(car.getC_desrspta_sub(), i, 19);

            if(String.valueOf(car.getF_fecasig_ult()).trim().length()>4){
             m.setValueAt(String.valueOf(car.getF_fecasig_ult()).substring(8, 10) + "/" +
             String.valueOf(car.getF_fecasig_ult()).substring(5, 7) + "/" +
             String.valueOf(car.getF_fecasig_ult()).substring(0, 4), i, 20);
            }else{
             m.setValueAt(car.getF_fecasig_ult(), i, 20); 
            }

            m.setValueAt(car.getId_codtcon(), i, 21);
            m.setValueAt(car.getC_destcon(), i, 22);
            m.setValueAt(car.getId_codtres(), i, 23);
            m.setValueAt(car.getC_destres(), i, 24);

            }this.jTable2.setModel(m);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
}//GEN-LAST:event_btn_mostrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
           Cartera car=new Cartera();
           String c_codcent_Ant= "";
           String c_codcent_act="";
           int i=0;

           int res=JOptionPane.showConfirmDialog(null, "Desea Registrar la Gestion de campo","Informacion",JOptionPane.YES_NO_OPTION);

           if(res==1){
             return;
           }else{
             while(i<jTable2.getRowCount()){
                c_codcent_act=jTable2.getValueAt(i, 1) + "";
                String f_proceso= String.valueOf(jTable2.getValueAt(i, 0)).substring(6, 10) + "-" +
                   String.valueOf(jTable2.getValueAt(i, 0)).substring(3, 5) + "-" +
                   String.valueOf(jTable2.getValueAt(i, 0)).substring(0, 2)  + " 00:00:00.000";

                  if(c_codcent_Ant.equals(c_codcent_act)){
                   System.out.println("no paso nada");
                  }else{
                   car.Asignacion_Cartera(c_codcent_act,f_proceso,"GCAMPO", "03","0");
                  }
                  c_codcent_Ant = c_codcent_act;
                  i=i+1;
              }
            JOptionPane.showMessageDialog(null, "Registros Gestion Campo Ingresados");
          }
        }catch(Exception ioE){
            JOptionPane.showMessageDialog(null, ioE);
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            JFileChooser caja=new JFileChooser();
            caja.showSaveDialog(null);
            File arch=caja.getSelectedFile();

            if(arch==null){
                return;
            }

            DataOutputStream out=new DataOutputStream(new FileOutputStream(arch + ".xls"));
            WritableWorkbook w = Workbook.createWorkbook(out);
            WritableSheet s = w.createSheet("reporte", 0);
            WritableFont headersfont=new WritableFont(WritableFont.ARIAL, 10, WritableFont.BOLD, false, UnderlineStyle.NO_UNDERLINE, Colour.WHITE);
            WritableCellFormat headersformat=new WritableCellFormat(headersfont);
            headersformat.setBackground(Colour.ORANGE);

            s.addCell(new Label(0, 0, String.valueOf("F_fproceso"),headersformat));
            s.addCell(new Label(1, 0, String.valueOf("C_codcent"),headersformat));
            s.addCell(new Label(2, 0, String.valueOf("Contrato"),headersformat));
            s.addCell(new Label(3, 0, String.valueOf("Tipo docu."),headersformat));
            s.addCell(new Label(4, 0, String.valueOf("nro_docu"),headersformat));
            s.addCell(new Label(5, 0, String.valueOf("Nombre"),headersformat));
            s.addCell(new Label(6, 0, String.valueOf("C_nomsubpro_car"),headersformat));
            s.addCell(new Label(7, 0, String.valueOf("C_nomsubpro"),headersformat));
            s.addCell(new Label(8, 0, String.valueOf("C_dessubpro"),headersformat));
            s.addCell(new Label(9, 0, String.valueOf("C_divisa_car"),headersformat));
            s.addCell(new Label(10, 0, String.valueOf("C_divisa"),headersformat));
            s.addCell(new Label(11, 0, String.valueOf("N_saldohoy"),headersformat));
            s.addCell(new Label(12, 0, String.valueOf("N_diasvenc"),headersformat));
            s.addCell(new Label(13, 0, String.valueOf("C_flgdir"),headersformat));
            s.addCell(new Label(14, 0, String.valueOf("C_dirimp"),headersformat));
            s.addCell(new Label(15, 0, String.valueOf("C_disimp"),headersformat));
            s.addCell(new Label(16, 0, String.valueOf("F_fproceso_ges"),headersformat));
            s.addCell(new Label(17, 0, String.valueOf("F_fecimp"),headersformat));
            s.addCell(new Label(18, 0, String.valueOf("C_desrspta"),headersformat));
            s.addCell(new Label(19, 0, String.valueOf("C_desrspta_sub"),headersformat));
            s.addCell(new Label(20, 0, String.valueOf("F_fecasig_ult"),headersformat));
            s.addCell(new Label(21, 0, String.valueOf("Id_codtcon"),headersformat));
            s.addCell(new Label(22, 0, String.valueOf("C_destcon"),headersformat));
            s.addCell(new Label(23, 0, String.valueOf("Id_codtres"),headersformat));
            s.addCell(new Label(24, 0, String.valueOf("C_destres"),headersformat));

             for(int i=0;i<jTable2.getRowCount();i++){

              for(int j=0;j<jTable2.getColumnCount();j++){
                 Object objeto=jTable2.getValueAt(i,j);
                 if(objeto!=null){
                    if(j==12){
                      s.addCell(new jxl.write.Number(j, i+1, Integer.parseInt(objeto + "")));
                    }else{
                      s.addCell(new Label(j, i+1, String.valueOf(objeto)));
                    }
                 }else{
                   s.addCell(new Label(j, i+1, ""));
                 }
               }
            }

            w.write();
            w.close();
            out.close();

           JOptionPane.showMessageDialog(null,"Reporte Terminado");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            String ruta;
            JFileChooser caja=new JFileChooser();
            caja.showOpenDialog(null);
            arch=caja.getSelectedFile();

            if(arch==null){
                return;
            }
            ruta=arch.getPath();
            lbl_ruta.setText(ruta);
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        try{
            if(lbl_ruta.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Seleccione Archivo a importar");
                return;
            }

            Workbook wb = Workbook.getWorkbook(arch);
            Sheet sheet = wb.getSheet(0);
            int rows = sheet.getRows();

            String nrodoc="";
            DefaultListModel l=new DefaultListModel();
            for(int i=0;i<rows;i++){
                nrodoc=sheet.getCell(0, i).getContents().trim();
                l.addElement(nrodoc);
            }jList2.setModel(l);
            lbln_regcar.setText(l.size() + "");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        lbl_ruta.setText("");
        jList2.setModel(new DefaultListModel());
}//GEN-LAST:event_jButton8ActionPerformed

    private void cbo_tipconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_tipconActionPerformed
        try{
        String id_codtcon="";
        if(cbo_tipcon.getSelectedItem()!="Todos"){
        id_codtcon=String.valueOf(cbo_tipcon.getSelectedItem()).substring(0, 2);
        }else{
        id_codtcon="";
        }

        cbo_tipres.removeAllItems();
        Gestion llm=new Gestion();
        ArrayList lista=new ArrayList();
        lista=llm.Respuesta_llam(id_codtcon);

        for(int i=0;i<lista.size();i++){
        llm=(Gestion)lista.get(i);
        cbo_tipres.addItem(llm.getId_codtres() + " - " + llm.getC_destres());
        }cbo_tipres.addItem("Todos");
        cbo_tipres.setSelectedItem("Todos");

        }catch(Exception ioE){

        }
    }//GEN-LAST:event_cbo_tipconActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JComboBox cbo_distrito;
    private javax.swing.JComboBox cbo_tipcon;
    private javax.swing.JComboBox cbo_tipres;
    private javax.swing.JSpinner dtpf_fecpro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField lbl_nroreg;
    private javax.swing.JTextPane lbl_ruta;
    private javax.swing.JTextField lbln_regcar;
    private javax.swing.JTextField txtc_nomcont;
    private javax.swing.JTextField txtc_numdoc;
    // End of variables declaration//GEN-END:variables

}
