
package FORMULARIOS;

import BEANS.Cartera;
import java.awt.Rectangle;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jxl.Sheet;
import jxl.Workbook;


   
public class frm_asignacion_campo extends javax.swing.JDialog {

        public File arch;
    
    public frm_asignacion_campo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ((javax.swing.JSpinner.DateEditor)dtpf_fproceso.getEditor()).getTextField().setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        btn_importar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_ruta = new javax.swing.JTextPane();
        dtpf_fproceso = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Seleccione Hoja de Calculo :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 50, 210, 18);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/open.JPG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(305, 75, 30, 30);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(3, 108, 252));
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(10, 120, 320, 22);

        btn_importar.setText("Importar");
        btn_importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_importar);
        btn_importar.setBounds(240, 145, 90, 30);

        lbl_ruta.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        lbl_ruta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_ruta.setForeground(java.awt.Color.blue);
        jScrollPane1.setViewportView(lbl_ruta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 290, 40);

        dtpf_fproceso.setModel(new javax.swing.SpinnerDateModel());
        dtpf_fproceso.setEditor(new javax.swing.JSpinner.DateEditor(dtpf_fproceso, "dd/MM/yyyy"));
        jPanel1.add(dtpf_fproceso);
        dtpf_fproceso.setBounds(125, 20, 100, 22);

        jLabel1.setText("Fecha proceso:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 22, 110, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 5, 350, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ruta;
        JFileChooser caja=new JFileChooser();
        caja.showOpenDialog(null);
        arch=caja.getSelectedFile();

        if(arch==null){
            return;
        }

        ruta=arch.getPath();
        lbl_ruta.setText(ruta);
}//GEN-LAST:event_jButton1ActionPerformed

    private void btn_importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importarActionPerformed

        try {
            Cartera car=new Cartera();
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String f_fproceso=sdf.format(dtpf_fproceso.getValue()) + " 00:00:00.000";

            if(lbl_ruta.getText().equals("")){
              JOptionPane.showMessageDialog(null, "Seleccione Archivo a importar");
              return;
            }
            
            Workbook wb = Workbook.getWorkbook(arch);
            Sheet sheet = wb.getSheet(0);
            //int columns = sheet.getColumns();
            int rows = sheet.getRows();
            int i=0;

            String c_codcent;

            jProgressBar1.setMaximum(rows);
            jProgressBar1.setMinimum(0);

            while(i<rows){

                jProgressBar1.setValue(i);
                jProgressBar1.setStringPainted(true);
                Rectangle progreso=jProgressBar1.getBounds();
                progreso.x=0;
                progreso.y=0;
                jProgressBar1.paintImmediately(progreso);

                c_codcent=sheet.getCell(0, i).getContents();
                if(c_codcent.isEmpty()){
                    JOptionPane.showMessageDialog(null,"error al ingresar el registro " + i);
                    i=i+1;
                }
                
                car.Asignacion_Cartera(c_codcent,f_fproceso ,"GCAMPO", "03", "0");

                i=i+1;
            }jProgressBar1.setValue(i);
            JOptionPane.showMessageDialog(null,"Asignacion campo Finalizada");
            jProgressBar1.setValue(0);

        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la Asignacion : " + e.getMessage());
            //        jProgressBar1.setValue(0);
        }
}//GEN-LAST:event_btn_importarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_asignacion_campo dialog = new frm_asignacion_campo(new javax.swing.JFrame(), true);
                dialog.setSize(367, 223);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_importar;
    private javax.swing.JSpinner dtpf_fproceso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane lbl_ruta;
    // End of variables declaration//GEN-END:variables

}
