
package FORMULARIOS;

import BEANS.Contacto;
import BEANS.Contratos;
import BEANS.Globales;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class frm_contacto_his extends javax.swing.JDialog {

    int idx_cab=0;
    int idx_det=0;
    int filas_con,filas_co;
    ArrayList dtSQL_Cab=new ArrayList();
    String fproceso,idxges,fecasig,codtges;

    void CargarDatos(){
     try{
     Globales glo=new Globales();
     Contacto co=new Contacto();
     dtSQL_Cab=co.contacto_gestion_historia(glo.getC_codcent(), glo.getF_fproceso(), glo.getId_codper());
     filas_co=dtSQL_Cab.size();
     idx_cab=dtSQL_Cab.size() - 1;
     this.Muesta_Gestion_Contacto(idx_cab);
     }catch(Exception ioE){
     JOptionPane.showMessageDialog(null, ioE);
     }
     }
       
//
      void Muesta_Gestion_Contacto(int idx){
        try{
         // SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
         Contacto co=new Contacto();
         co=(Contacto)dtSQL_Cab.get(idx);

         txtf_fecasig.setText(String.valueOf(co.getF_fecasig()).substring(0, 10));
         txtc_tipodoc.setText(co.getC_tipodoc());
         txtc_nrodoc.setText(co.getC_nrodoc());
         txtc_tpersona.setText(co.getC_tpersona());
         txtc_nombre.setText(co.getC_nombre());
         txtc_destges.setText(co.getC_destges());

         fproceso=co.getF_fproceso();
         idxges=co.getN_idxges();
         fecasig=co.getF_fecasig();
         codtges=co.getId_codtges();

         lblc_numreg_con.setText("Contrato: " + (idx_cab + 1) + " de " + dtSQL_Cab.size());

         this.Muestra_Gestion_Contrato(idx_det);

        }catch(Exception ioE){
        JOptionPane.showMessageDialog(null, ioE);
       }
     }
    

      void Muestra_Gestion_Contrato(int idx){
      try{
         Contratos con=new Contratos();
         Globales glo=new Globales();
         ArrayList lista=new ArrayList();
         lista=con.contrato_gestion_historia(fproceso, glo.getId_codper(), glo.getC_codcent(),Integer.parseInt(idxges),
         fecasig,codtges);
         filas_con=lista.size();
         lbl_contador1.setText("Contrato: " + (idx_det + 1) + " de " + filas_con);
         con=(Contratos)lista.get(idx);
//       idx_det = lista.size()-1;
         txtc_contrato.setText(con.getC_contrato());
         txtc_subprod.setText(con.getC_subprod());
         txtc_nomsubpro.setText(con.getC_nomsubpro());
         txtc_dessubpro.setText(con.getC_dessubpro());
         txtc_divisa.setText(con.getC_divisa());
         txtn_saldohoy.setText(con.getN_saldohoy());
         txtf_fincumpli.setText(String.valueOf(con.getF_fincumpli()).substring(0, 10));
         txtn_diasvenc.setText(con.getN_diasvenc());
         txtn_impprov.setText(con.getN_impprov());
         txtn_deutotobli.setText(con.getN_deutotobli());
         txtn_deutotclie.setText(con.getN_deutotclie());
         txtc_destcon.setText(con.getC_destcon());
         txtc_destres.setText(con.getC_destres());
         txtc_numubi.setText(con.getC_numubi());

         String f_fecresp = "";
         if(con.getF_fecresp()==null){
         f_fecresp="";
         }else{
         f_fecresp=con.getF_fecresp();
        }
         txtf_fecresp.setText(f_fecresp);

         txtc_destres_sub.setText(con.getC_destres_sub());
         txtc_obsges.setText(con.getC_obsges());

      }catch(Exception ioE){
//      JOptionPane.showMessageDialog(null, ioE);
      }
      }

    public frm_contacto_his(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       this.CargarDatos();
       this.Muestra_Gestion_Contrato(idx_det);
          
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar2 = new javax.swing.JToolBar();
        btn_anterior = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        lblc_numreg_con = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtf_fecasig = new javax.swing.JTextField();
        txtc_nombre = new javax.swing.JTextField();
        txtc_tipodoc = new javax.swing.JTextField();
        txtc_nrodoc = new javax.swing.JTextField();
        txtc_tpersona = new javax.swing.JTextField();
        txtc_destges = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtc_contrato = new javax.swing.JTextField();
        txtc_divisa = new javax.swing.JTextField();
        txtn_impprov = new javax.swing.JTextField();
        txtc_destcon = new javax.swing.JTextField();
        txtf_fecresp = new javax.swing.JTextField();
        txtn_diasvenc = new javax.swing.JTextField();
        txtn_saldohoy = new javax.swing.JTextField();
        txtc_destres = new javax.swing.JTextField();
        txtf_fincumpli = new javax.swing.JTextField();
        txtc_subprod = new javax.swing.JTextField();
        txtc_nomsubpro = new javax.swing.JTextField();
        txtc_dessubpro = new javax.swing.JTextField();
        txtn_deutotobli = new javax.swing.JTextField();
        txtn_deutotclie = new javax.swing.JTextField();
        txtc_destres_sub = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtc_obsges = new javax.swing.JTextPane();
        jToolBar3 = new javax.swing.JToolBar();
        btn_anterior1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        lbl_contador1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtc_numubi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jToolBar2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        btn_anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Anterior1.JPG"))); // NOI18N
        btn_anterior.setText("Anterior");
        btn_anterior.setFocusable(false);
        btn_anterior.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_anterior.setMaximumSize(new java.awt.Dimension(85, 21));
        btn_anterior.setMinimumSize(new java.awt.Dimension(65, 21));
        btn_anterior.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_anteriorMouseClicked(evt);
            }
        });
        btn_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anteriorActionPerformed(evt);
            }
        });
        jToolBar2.add(btn_anterior);

        jLabel14.setText("Contacto");
        jToolBar2.add(jLabel14);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Siguiente1.JPG"))); // NOI18N
        jButton11.setText("Siguiente");
        jButton11.setFocusable(false);
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton11.setMaximumSize(new java.awt.Dimension(85, 21));
        jButton11.setMinimumSize(new java.awt.Dimension(71, 21));
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton11);

        lblc_numreg_con.setForeground(new java.awt.Color(0, 51, 204));
        lblc_numreg_con.setText(" 1 Cuenta de 2  ");
        jToolBar2.add(lblc_numreg_con);

        getContentPane().add(jToolBar2);
        jToolBar2.setBounds(1, 1, 680, 30);

        jLabel15.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel15.setText("Fecha Gestion:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 45, 95, 17);

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel16.setText("Nombres:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(10, 70, 68, 17);

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel17.setText("Tipo y Nº Docu.:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(200, 45, 100, 17);

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel18.setText("Tip. Persona:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(425, 45, 80, 17);

        jLabel19.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel19.setText("Tipo Gestion:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(380, 70, 84, 17);

        txtf_fecasig.setEditable(false);
        getContentPane().add(txtf_fecasig);
        txtf_fecasig.setBounds(110, 42, 80, 22);

        txtc_nombre.setEditable(false);
        getContentPane().add(txtc_nombre);
        txtc_nombre.setBounds(100, 67, 270, 22);

        txtc_tipodoc.setEditable(false);
        getContentPane().add(txtc_tipodoc);
        txtc_tipodoc.setBounds(305, 42, 30, 22);

        txtc_nrodoc.setEditable(false);
        getContentPane().add(txtc_nrodoc);
        txtc_nrodoc.setBounds(338, 42, 75, 22);

        txtc_tpersona.setEditable(false);
        getContentPane().add(txtc_tpersona);
        txtc_tpersona.setBounds(510, 42, 80, 22);

        txtc_destges.setEditable(false);
        getContentPane().add(txtc_destges);
        txtc_destges.setBounds(470, 67, 120, 22);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.blue)); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel3.setText("Imp. Provision:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 110, 95, 17);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel2.setText("Saldo Actual:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(12, 85, 85, 17);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel1.setText("Nº Contrato :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 60, 85, 17);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel7.setText("Sub Producto:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(235, 60, 90, 17);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel8.setText("Fecha Cumpli.:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(235, 85, 95, 17);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel9.setText("Deu. Total Obligatorio:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(192, 110, 145, 17);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel12.setText("Dias Venc.:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(430, 85, 75, 17);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel13.setText("Deuda  Cliente:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(420, 110, 100, 17);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel6.setText("Observacion:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(12, 180, 85, 17);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel5.setText("Fecha Hora Rspt:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(12, 160, 110, 17);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel4.setText("Tip. Contacto:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 136, 90, 17);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel10.setText("Tip. Respuesta:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(256, 136, 100, 17);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel11.setText("Det. No Desea:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(220, 160, 95, 17);

        txtc_contrato.setEditable(false);
        jPanel1.add(txtc_contrato);
        txtc_contrato.setBounds(110, 57, 110, 22);

        txtc_divisa.setEditable(false);
        jPanel1.add(txtc_divisa);
        txtc_divisa.setBounds(110, 83, 29, 22);

        txtn_impprov.setEditable(false);
        jPanel1.add(txtn_impprov);
        txtn_impprov.setBounds(110, 108, 75, 22);

        txtc_destcon.setEditable(false);
        jPanel1.add(txtc_destcon);
        txtc_destcon.setBounds(110, 133, 140, 22);

        txtf_fecresp.setEditable(false);
        jPanel1.add(txtf_fecresp);
        txtf_fecresp.setBounds(122, 158, 90, 22);

        txtn_diasvenc.setEditable(false);
        jPanel1.add(txtn_diasvenc);
        txtn_diasvenc.setBounds(507, 82, 70, 22);

        txtn_saldohoy.setEditable(false);
        jPanel1.add(txtn_saldohoy);
        txtn_saldohoy.setBounds(141, 83, 80, 22);

        txtc_destres.setEditable(false);
        jPanel1.add(txtc_destres);
        txtc_destres.setBounds(360, 133, 303, 22);

        txtf_fincumpli.setEditable(false);
        jPanel1.add(txtf_fincumpli);
        txtf_fincumpli.setBounds(338, 82, 78, 22);

        txtc_subprod.setEditable(false);
        jPanel1.add(txtc_subprod);
        txtc_subprod.setBounds(330, 57, 48, 22);

        txtc_nomsubpro.setEditable(false);
        jPanel1.add(txtc_nomsubpro);
        txtc_nomsubpro.setBounds(380, 57, 88, 22);

        txtc_dessubpro.setEditable(false);
        jPanel1.add(txtc_dessubpro);
        txtc_dessubpro.setBounds(470, 57, 140, 22);

        txtn_deutotobli.setEditable(false);
        jPanel1.add(txtn_deutotobli);
        txtn_deutotobli.setBounds(340, 108, 70, 22);

        txtn_deutotclie.setEditable(false);
        jPanel1.add(txtn_deutotclie);
        txtn_deutotclie.setBounds(525, 108, 70, 22);

        txtc_destres_sub.setEditable(false);
        jPanel1.add(txtc_destres_sub);
        txtc_destres_sub.setBounds(320, 158, 350, 22);

        txtc_obsges.setEditable(false);
        jScrollPane1.setViewportView(txtc_obsges);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(110, 185, 350, 78);

        jToolBar3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar3.setRollover(true);

        btn_anterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Anterior1.JPG"))); // NOI18N
        btn_anterior1.setText("Anterior");
        btn_anterior1.setFocusable(false);
        btn_anterior1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_anterior1.setMaximumSize(new java.awt.Dimension(85, 21));
        btn_anterior1.setMinimumSize(new java.awt.Dimension(65, 21));
        btn_anterior1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_anterior1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_anterior1MouseClicked(evt);
            }
        });
        btn_anterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_anterior1ActionPerformed(evt);
            }
        });
        jToolBar3.add(btn_anterior1);

        jLabel20.setText("Contacto");
        jToolBar3.add(jLabel20);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Siguiente1.JPG"))); // NOI18N
        jButton12.setText("Siguiente");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton12.setMaximumSize(new java.awt.Dimension(85, 21));
        jButton12.setMinimumSize(new java.awt.Dimension(71, 21));
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jToolBar3.add(jButton12);

        lbl_contador1.setForeground(new java.awt.Color(0, 51, 204));
        lbl_contador1.setText(" 1 Cuenta de 2  ");
        jToolBar3.add(lbl_contador1);

        jPanel1.add(jToolBar3);
        jToolBar3.setBounds(2, 18, 675, 30);

        jLabel21.setText("T. ubicado :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(470, 190, 82, 18);
        jPanel1.add(txtc_numubi);
        txtc_numubi.setBounds(556, 189, 100, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 95, 680, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anteriorMouseClicked

}//GEN-LAST:event_btn_anteriorMouseClicked

    private void btn_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anteriorActionPerformed
        if(idx_cab>0){
           idx_cab=idx_cab-1; 
           this.Muesta_Gestion_Contacto(idx_cab);
        }
      
}//GEN-LAST:event_btn_anteriorActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if(idx_cab<filas_co-1){
           idx_cab=idx_cab+1;
           this.Muesta_Gestion_Contacto(idx_cab);
        }
       
}//GEN-LAST:event_jButton11ActionPerformed

    private void btn_anterior1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_anterior1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_anterior1MouseClicked

    private void btn_anterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_anterior1ActionPerformed
      if(idx_det>0){
         idx_det=idx_det-1;
      }
      this.Muestra_Gestion_Contrato(idx_det);
    }//GEN-LAST:event_btn_anterior1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     if(idx_det<filas_con-1){
        idx_det=idx_det+1;
     }
        this.Muestra_Gestion_Contrato(idx_det);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
          //      frm_contacto_his dialog = new frm_contacto_his(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });

//                dialog.setSize(690, 390);
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_anterior;
    private javax.swing.JButton btn_anterior1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JLabel lbl_contador1;
    private javax.swing.JLabel lblc_numreg_con;
    private javax.swing.JTextField txtc_contrato;
    private javax.swing.JTextField txtc_dessubpro;
    private javax.swing.JTextField txtc_destcon;
    private javax.swing.JTextField txtc_destges;
    private javax.swing.JTextField txtc_destres;
    private javax.swing.JTextField txtc_destres_sub;
    private javax.swing.JTextField txtc_divisa;
    private javax.swing.JTextField txtc_nombre;
    private javax.swing.JTextField txtc_nomsubpro;
    private javax.swing.JTextField txtc_nrodoc;
    private javax.swing.JTextField txtc_numubi;
    private javax.swing.JTextPane txtc_obsges;
    private javax.swing.JTextField txtc_subprod;
    private javax.swing.JTextField txtc_tipodoc;
    private javax.swing.JTextField txtc_tpersona;
    private javax.swing.JTextField txtf_fecasig;
    private javax.swing.JTextField txtf_fecresp;
    private javax.swing.JTextField txtf_fincumpli;
    private javax.swing.JTextField txtn_deutotclie;
    private javax.swing.JTextField txtn_deutotobli;
    private javax.swing.JTextField txtn_diasvenc;
    private javax.swing.JTextField txtn_impprov;
    private javax.swing.JTextField txtn_saldohoy;
    // End of variables declaration//GEN-END:variables

}
