
package FORMULARIOS;

import BEANS.Gestion;
import BEANS.Globales;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frm_cartera_Ges extends javax.swing.JDialog {

    public static Object formulario;


    void listado(){
      try{
       String nrodoc,nombre;
       nrodoc=txtc_nrodoc.getText();
       nombre=txtc_nomcont.getText();

       Gestion ges=new Gestion();
       Globales glo=new Globales();
       ArrayList lista=new ArrayList();

       String tipges="";

       if(cbo_tipges.getSelectedItem()=="Todos"){
       tipges="";
       }else{
       tipges=(cbo_tipges.getSelectedItem() + "").substring(0, 2);
       }
       lista=ges.lista_gestion_contacto(glo.getId_codper(), txtc_nrodoc.getText().trim(),
       txtc_nomcont.getText().trim(), tipges);
       lbl_nroreg.setText(lista.size() + "");

       DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
       m.setRowCount(lista.size());

       for(int i=0;i<lista.size();i++){
       ges=(Gestion)lista.get(i);
       m.setValueAt(String.valueOf(ges.getF_fproceso()).substring(8, 10) + "/" +
       String.valueOf(ges.getF_fproceso()).substring(5, 7) + "/" + 
       String.valueOf(ges.getF_fproceso()).substring(0, 4), i, 0);

       m.setValueAt(String.valueOf(ges.getF_fecasig()).substring(8, 10) + "/" + 
       String.valueOf(ges.getF_fecasig()).substring(5, 7) + "/" + 
       String.valueOf(ges.getF_fecasig()).substring(0, 4), i, 1);

       m.setValueAt(ges.getC_codcent(), i, 2);
       m.setValueAt(ges.getC_tipodoc(), i, 3);
       m.setValueAt(ges.getC_nrodoc(), i, 4);
       m.setValueAt(ges.getC_nombre(), i, 5);
       m.setValueAt(ges.getC_direccion(), i, 6);
       m.setValueAt(ges.getC_distprov(), i, 7);
       m.setValueAt(ges.getC_telefono(), i, 8);
       m.setValueAt(ges.getC_destges(), i, 9);
       m.setValueAt(ges.getN_idxges(), i, 10);
       m.setValueAt(ges.getId_codusu(), i, 11);
       m.setValueAt(ges.getId_codtges(), i, 12);
       }this.jTable1.setModel(m);
       }catch(Exception ioE){
       JOptionPane.showMessageDialog(null, ioE);
       }

    }

    public frm_cartera_Ges(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        formulario = this;

        cbo_tipges.removeAllItems();
        cbo_tipges.addItem("01 - LLAMADA");
        cbo_tipges.addItem("02 - CARTA");
        cbo_tipges.addItem("03 - VISITA");
        cbo_tipges.addItem("Todos");
        cbo_tipges.setSelectedItem("Todos");
            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtc_nrodoc = new javax.swing.JTextField();
        cbo_tipges = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtc_nomcont = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_nroreg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Gestion Contacto");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios de Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.blue)); // NOI18N
        jPanel1.setLayout(null);

        txtc_nrodoc.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jPanel1.add(txtc_nrodoc);
        txtc_nrodoc.setBounds(88, 28, 100, 22);

        cbo_tipges.setFont(new java.awt.Font("Ubuntu", 0, 14));
        cbo_tipges.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_tipges);
        cbo_tipges.setBounds(88, 55, 170, 22);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel1.setText("Nº Docu :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 60, 17);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel2.setText("Gestion :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 57, 60, 17);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel3.setText("Apellidos y Nombres :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 30, 140, 17);

        txtc_nomcont.setFont(new java.awt.Font("Ubuntu", 0, 14));
        txtc_nomcont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtc_nomcontKeyTyped(evt);
            }
        });
        jPanel1.add(txtc_nomcont);
        txtc_nomcont.setBounds(345, 28, 350, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 55, 880, 90);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Proceso", "Fecha Asignado", "c_codcent", "Tip. Docu.", "Nº Docu.", "Nombres", "Dirección", "Provincia Distrito", "Telefono", "Tipo Gestion", "Indice Gestion", "id_codusu", "id_codtges"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(95);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(95);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(95);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(75);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(260);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(310);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(12).setPreferredWidth(85);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 870, 390);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mostrar.JPG"))); // NOI18N
        jButton1.setText("Mostrar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 960, 50);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel9.setText("Nº Registros :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(15, 7, 85, 17);

        lbl_nroreg.setEditable(false);
        lbl_nroreg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lbl_nroreg.setText("0");
        jPanel2.add(lbl_nroreg);
        lbl_nroreg.setBounds(105, 4, 60, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 560, 960, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.listado();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      try{
      if(evt.getClickCount()==2){        
        int fila=jTable1.getSelectedRow();
        SimpleDateFormat sdf=new SimpleDateFormat("dd-MM-yyyy");
        Globales glo=new Globales();
        glo.setC_codcent(jTable1.getValueAt(fila, 2) + "");

        glo.setF_fproceso(String.valueOf(jTable1.getValueAt(fila, 0)).substring(6, 10)  + "-" +
        String.valueOf(jTable1.getValueAt(fila, 0)).substring(3, 5)  + "-" +
        String.valueOf(jTable1.getValueAt(fila, 0)).substring(0, 2) + " 00:00:00.000");

        glo.setIdxges(jTable1.getValueAt(fila, 10) + "");
        glo.setId_codusu2(jTable1.getValueAt(fila, 11) + "");
        glo.setId_codtges(jTable1.getValueAt(fila, 12) + "");
        frm_llamada_ges frm = new frm_llamada_ges(new javax.swing.JFrame(), true);
        frm.setSize(960, 700);
        frm.setVisible(true);
      }
      }catch(Exception ioE){
      JOptionPane.showMessageDialog(null, ioE);    
      }
        
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtc_nomcontKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtc_nomcontKeyTyped
       char caracter=evt.getKeyChar();
       evt.setKeyChar(Character.toUpperCase(caracter));
    }//GEN-LAST:event_txtc_nomcontKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_cartera_Ges dialog = new frm_cartera_Ges(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
                dialog.setSize(900, 623);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbo_tipges;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField lbl_nroreg;
    private javax.swing.JTextField txtc_nomcont;
    private javax.swing.JTextField txtc_nrodoc;
    // End of variables declaration//GEN-END:variables

}
