
package FORMULARIOS;

import BEANS.Globales;
import BEANS.Periodo;
import java.util.ArrayList;
import javax.swing.DefaultListModel;


public class frm_periodo extends javax.swing.JDialog {


    void cargar(){
    try{
    Periodo per=new Periodo();
    ArrayList lista=new ArrayList();
    lista=per.listado_periodos();
    DefaultListModel l=new DefaultListModel();
    for(int i=0;i<lista.size();i++){
    per=(Periodo)lista.get(i);
    l.addElement(per.getC_desper());
    }jList1.setModel(l);

    }catch(Exception e){

    }
    }

    public frm_periodo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.cargar();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Periodo");
        getContentPane().setLayout(null);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 190, 110);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        Globales glo=new Globales();
        int click=evt.getClickCount();
        
        if(click==2){
        int num=(jList1.getSelectedValue()+"").length();
        glo.setId_codper(String.valueOf(jList1.getSelectedValue()).substring(0, 3) +
        String.valueOf(jList1.getSelectedValue()).substring(num-2, num));
        glo.setC_desper(String.valueOf(jList1.getSelectedValue()).trim());
        
        frm_principal frm=(frm_principal)frm_principal.principal;
        frm.mostrar();
        this.dispose();
       }
    }//GEN-LAST:event_jList1MouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_periodo dialog = new frm_periodo(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
                dialog.setSize(197, 143);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
