
package FORMULARIOS;

import BEANS.Globales;
import BEANS.Periodo;
import BEANS.Usuario;
import de.javasoft.plaf.synthetica.SyntheticaStandardLookAndFeel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


public class frm_ingreso extends javax.swing.JFrame {


    void Cargar(){
    try{
    cbo_periodo.removeAllItems();
    Periodo per=new Periodo();    
    ArrayList lista=new ArrayList();
    lista=per.listado_periodos();
   
    for(int i=0;i<lista.size();i++){
    per=(Periodo)lista.get(i);
    cbo_periodo.addItem(per.getC_desper());
    }    
    }catch(Exception e){

    }    
    }


    public frm_ingreso() {
        initComponents();
        this.Cargar();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_codusu = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbo_periodo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ingreso");
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/administrador.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 280, 210);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel2.setText("Usuario :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(35, 235, 57, 17);

        txt_codusu.setFont(new java.awt.Font("Ubuntu", 1, 13));
        txt_codusu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codusuKeyTyped(evt);
            }
        });
        getContentPane().add(txt_codusu);
        txt_codusu.setBounds(100, 232, 160, 22);

        txt_pass.setFont(new java.awt.Font("Ubuntu", 1, 13));
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passKeyTyped(evt);
            }
        });
        getContentPane().add(txt_pass);
        txt_pass.setBounds(100, 258, 160, 22);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel3.setText("Contraseña :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(15, 261, 82, 17);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel4.setText("Periodo :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(35, 287, 62, 17);

        cbo_periodo.setFont(new java.awt.Font("Ubuntu", 0, 13));
        cbo_periodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbo_periodo);
        cbo_periodo.setBounds(100, 284, 160, 22);

        jButton1.setText("Ingreso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(32, 318, 105, 22);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(144, 318, 105, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try{
    frm_principal frm;
    Globales glo=new Globales();
    Usuario usu=new Usuario();
    ArrayList lista=new ArrayList();
    lista=usu.logueo(txt_codusu.getText().trim() + "", txt_pass.getText().trim() + "");
    String nombre=usu.Nombre_usuario(txt_codusu.getText().trim());
    String nomper=String.valueOf(cbo_periodo.getSelectedItem()).trim();
    
    if(lista.size()>0){
      glo.setC_nomusu(nombre);
      glo.setId_codusu(txt_codusu.getText().trim());
      glo.setId_codper(String.valueOf(cbo_periodo.getSelectedItem()).substring(0, 3) +
      String.valueOf(cbo_periodo.getSelectedItem()).substring(nomper.length() - 2, nomper.length()));
      glo.setC_desper(nomper);
      
      int x = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
      int y = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;

      frm=new frm_principal(x,y);
      frm.setSize(x, y);
      frm.setVisible(true);
      this.dispose();

    }else{
    JOptionPane.showMessageDialog(null, "Usuario i/o Contraseña Incorrecta", "Ventana Error", JOptionPane.ERROR_MESSAGE);
    }
    }catch(Exception e){
        
    }  

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
}//GEN-LAST:event_jButton2ActionPerformed

    private void txt_codusuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codusuKeyTyped
        char caracter=evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(caracter));
    }//GEN-LAST:event_txt_codusuKeyTyped

    private void txt_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyTyped
        char caracter=evt.getKeyChar();
        evt.setKeyChar(Character.toUpperCase(caracter));
    }//GEN-LAST:event_txt_passKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            try{

            UIManager.put("Synthetica.window.decoration", Boolean.FALSE);
            UIManager.setLookAndFeel(new SyntheticaStandardLookAndFeel());

            }catch(Exception e){
             JOptionPane.showMessageDialog(null, e.getMessage());
            }

                frm_ingreso frm=new frm_ingreso();
                frm.setSize(293, 390);
                frm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbo_periodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_codusu;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables

}
