
package FORMULARIOS;

import BEANS.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class frm_usuario_mant extends javax.swing.JDialog {

    public String accion="";

    void mostrar(){
    try{
     int fila=jTable1.getSelectedRow();
        txtid_codusu.setText(this.jTable1.getValueAt(fila, 0) + "");
        txtc_nomusu.setText(this.jTable1.getValueAt(fila, 1) + "");
        txtc_passusu.setText(this.jTable1.getValueAt(fila, 2)+"");
        String tipo=this.jTable1.getValueAt(fila, 3)+"";
        String estado=this.jTable1.getValueAt(fila, 4)+"";

        if(tipo.equals("GES")){
        cbo_tipusu.setSelectedItem("GES - GESTION");
        }else{
        cbo_tipusu.setSelectedItem("ADM - ADMINISTRADOR");
        }

        if(estado.equals("ACT")){
        cbo_estusu.setSelectedItem("ACT - ACTIVO");
        }else{
        cbo_estusu.setSelectedItem("INA - INACTIVO");
        }
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }

    void cargar(){
    try{
    Usuario usu=new Usuario();
    ArrayList lista=new ArrayList();
    lista=usu.listado_usuarios();

    DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
    m.setNumRows(lista.size());

    for(int i=0;i<lista.size();i++){
    usu=(Usuario)lista.get(i);
    m.setValueAt(usu.getId_codusu(), i, 0);
    m.setValueAt(usu.getC_nomusu(), i, 1);
    m.setValueAt(usu.getC_passusu(), i, 2);
    m.setValueAt(usu.getC_tipusu(), i, 3);
    m.setValueAt(usu.getC_codest(), i, 4);
    }this.jTable1.setModel(m);
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }


    public frm_usuario_mant(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        cbo_tipusu.removeAllItems();
        cbo_estusu.removeAllItems();

        cbo_tipusu.addItem("ADM - ADMINISTRADOR");
        cbo_tipusu.addItem("GES - GESTION");
        cbo_estusu.addItem("ACT - ACTIVO");
        cbo_estusu.addItem("INA - INACTIVO");

        cbo_tipusu.setSelectedItem("GES - GESTION");
        cbo_estusu.setSelectedItem("ACT - ACTIVO");
        btn_grabar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        cbo_tipusu.setEnabled(false);
        cbo_estusu.setEnabled(false);
        txtid_codusu.setEditable(false);
        txtc_nomusu.setEditable(false);
        txtc_passusu.setEditable(false);
        this.cargar();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtid_codusu = new javax.swing.JTextField();
        txtc_nomusu = new javax.swing.JTextField();
        txtc_passusu = new javax.swing.JTextField();
        cbo_tipusu = new javax.swing.JComboBox();
        cbo_estusu = new javax.swing.JComboBox();
        jToolBar1 = new javax.swing.JToolBar();
        btn_nuevo = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_grabar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento Usuarios");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Contraseña", "Tipo", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 570, 270);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel1.setText("Cód. Usuario:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(18, 18, 87, 17);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel2.setText("Nombres Usuarios:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(18, 44, 120, 17);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel3.setText("Contraseña:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(18, 72, 80, 17);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel4.setText("Tipo Usuario:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(18, 100, 82, 17);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel5.setText("Estado:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(18, 127, 55, 17);
        jPanel1.add(txtid_codusu);
        txtid_codusu.setBounds(140, 13, 130, 22);
        jPanel1.add(txtc_nomusu);
        txtc_nomusu.setBounds(140, 41, 220, 22);
        jPanel1.add(txtc_passusu);
        txtc_passusu.setBounds(140, 69, 140, 22);

        cbo_tipusu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_tipusu);
        cbo_tipusu.setBounds(140, 97, 160, 22);

        cbo_estusu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_estusu);
        cbo_estusu.setBounds(140, 125, 110, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(6, 40, 590, 440);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btn_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.JPG"))); // NOI18N
        btn_nuevo.setFocusable(false);
        btn_nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_nuevo);

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificar.JPG"))); // NOI18N
        btn_modificar.setFocusable(false);
        btn_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_modificar);

        btn_grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grabar.JPG"))); // NOI18N
        btn_grabar.setFocusable(false);
        btn_grabar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_grabar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grabarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_grabar);

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/traspaso.JPG"))); // NOI18N
        btn_cancelar.setFocusable(false);
        btn_cancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_cancelar);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 600, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        try{
        txtid_codusu.setText("");
        txtc_nomusu.setText("");
        txtc_passusu.setText("");

        txtid_codusu.setEditable(true);
        txtc_nomusu.setEditable(true);
        txtc_passusu.setEditable(true);

        cbo_tipusu.setEnabled(true);
        cbo_estusu.setEnabled(true);

        btn_grabar.setEnabled(true);
        btn_cancelar.setEnabled(true);
        accion="new";
        }catch(Exception ioE){
        JOptionPane.showMessageDialog(null, ioE);
        }
}//GEN-LAST:event_btn_nuevoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       try{
       if(accion.equals("new")){
       return;
       }else{
        int fila=jTable1.getSelectedRow();
        txtid_codusu.setText(this.jTable1.getValueAt(fila, 0) + "");
        txtc_nomusu.setText(this.jTable1.getValueAt(fila, 1) + "");
        txtc_passusu.setText(this.jTable1.getValueAt(fila, 2)+"");
        String tipo=this.jTable1.getValueAt(fila, 3)+"";
        String estado=this.jTable1.getValueAt(fila, 4)+"";

            if(tipo.equals("GES")){
            cbo_tipusu.setSelectedItem("GES - GESTION");
            }else{
            cbo_tipusu.setSelectedItem("ADM - ADMINISTRADOR");
            }

            if(estado.equals("ACT")){
            cbo_estusu.setSelectedItem("ACT - ACTIVO");
            }else{
            cbo_estusu.setSelectedItem("INA - INACTIVO");
            }
        }

        }catch(Exception ioE){
        JOptionPane.showMessageDialog(null, ioE);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
      
        btn_grabar.setEnabled(true);
        btn_cancelar.setEnabled(true);
        txtid_codusu.setEditable(false);
        txtc_nomusu.setEditable(true);
        txtc_passusu.setEditable(true);
        cbo_tipusu.setEnabled(true);
        cbo_estusu.setEnabled(true);
        this.mostrar();
        accion="mod";
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed

        accion="";
        this.mostrar();
        txtid_codusu.setEditable(false);
        txtc_nomusu.setEditable(false);
        txtc_passusu.setEditable(false);

        cbo_tipusu.setEnabled(false);
        cbo_estusu.setEnabled(false);

        btn_grabar.setEnabled(false);
        btn_cancelar.setEnabled(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grabarActionPerformed
      try{

        Usuario usu=new Usuario();
        if(accion.equals("new")){
          if(txtid_codusu.getText().trim().isEmpty()){
          JOptionPane.showMessageDialog(null, "Ventana Error","Ingrese Codigo Usuario",JOptionPane.ERROR_MESSAGE);
          return;
          }
          }

          if(txtc_nomusu.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Ventana Error","Ingrese Nombres Usuario",JOptionPane.ERROR_MESSAGE);
          return;
          }

          if(txtc_passusu.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Ventana Error","Ingrese Contraseña Usuario",JOptionPane.ERROR_MESSAGE);
          return;
          }

        String c_tipusu=(cbo_tipusu.getSelectedItem() + "").substring(0, 3);
        String c_codest=(cbo_estusu.getSelectedItem() + "").substring(0, 3);

        usu.graba_usuario(txtid_codusu.getText(), txtc_nomusu.getText(), txtc_passusu.getText(),
        c_tipusu, c_codest, accion);
        btn_cancelar.setSelected(true);
        btn_grabar.setEnabled(false);
        btn_cancelar.setEnabled(false);
        this.cargar();
      }catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
      }

    }//GEN-LAST:event_btn_grabarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_usuario_mant dialog = new frm_usuario_mant(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
                dialog.setSize(600, 550);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_grabar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JComboBox cbo_estusu;
    private javax.swing.JComboBox cbo_tipusu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtc_nomusu;
    private javax.swing.JTextField txtc_passusu;
    private javax.swing.JTextField txtid_codusu;
    // End of variables declaration//GEN-END:variables

}
