
package FORMULARIOS;

import BEANS.Globales;
import BEANS.Reportes;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.Label;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;


public class frm_reporte_impresion_cartas extends javax.swing.JDialog {

    /** Creates new form frm_reporte_gestweb */
    public frm_reporte_impresion_cartas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         ((javax.swing.JSpinner.DateEditor)dtp_fproceso.getEditor()).getTextField().setEditable(false);
         
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dtp_fproceso = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtc_nrodoc = new javax.swing.JTextField();
        txtc_nomcont = new javax.swing.JTextField();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_nroreg = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte Impresion Cartas");
        getContentPane().setLayout(null);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mostrar.JPG"))); // NOI18N
        jButton1.setText("Mostrar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.JPG"))); // NOI18N
        jButton2.setText("Exportar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 895, 50);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios de Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.blue)); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel1.setText("Fecha Proceso :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 100, 16);

        dtp_fproceso.setModel(new javax.swing.SpinnerDateModel());
        dtp_fproceso.setEditor(new javax.swing.JSpinner.DateEditor(dtp_fproceso, "dd/MM/yyyy"));
        jPanel1.add(dtp_fproceso);
        dtp_fproceso.setBounds(125, 27, 100, 22);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel2.setText("Nº Docu.:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(240, 30, 62, 16);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel4.setText("Nombres:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(405, 30, 62, 16);
        jPanel1.add(txtc_nrodoc);
        txtc_nrodoc.setBounds(305, 27, 85, 22);
        jPanel1.add(txtc_nomcont);
        txtc_nomcont.setBounds(475, 27, 180, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 55, 880, 60);

        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(10, 120, 875, 25);

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "c_codcent", "c_nrodoc", "c_nombre", "c_direccion", "c_distprov", "max_diasvenc", "direccion_encontrada", "distrito_encontrado", "c_contrato_1", "c_dessubpro_1", "c_nomsubpro_1", "c_divisa_1", "n_saldohoy_1", "n_diasvenc_1", "c_contrato_2", "c_dessubpro_2", "c_nomsubpro_2", "c_divisa_2", "n_saldohoy_2", "n_diasvenc_2", "c_contrato_3", "c_dessubpro_3", "c_nomsubpro_3", "c_divisa_3", "n_saldohoy_3", "n_diasvenc_3", "c_contrato_4", "c_dessubpro_4", "c_nomsubpro_4", "c_divisa_4", "n_saldohoy_4", "n_diasvenc_4", "c_contrato_5", "c_dessubpro_5", "c_nomsubpro_5", "c_divisa_5", "n_saldohoy_5", "n_diasvenc_5", "c_contrato_6", "c_dessubpro_6", "c_nomsubpro_6", "c_divisa_6", "n_saldohoy_6", "n_diasvenc_6", "f_fecimp_ult", "c_codrspta", "c_desrspta_sub", "f_fproceso", "c_destcon", "c_destres", "cuad_plano", "cuad_x", "cuad_y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(220);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(350);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(130);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(200);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(130);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(12).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(13).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(14).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(15).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(16).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(17).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(18).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(19).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(20).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(21).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(22).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(23).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(24).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(25).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(26).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(27).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(28).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(29).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(30).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(31).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(32).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(33).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(34).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(35).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(36).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(37).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(38).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(39).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(41).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(42).setPreferredWidth(90);
        jTable1.getColumnModel().getColumn(43).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(50).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(51).setPreferredWidth(80);
        jTable1.getColumnModel().getColumn(52).setPreferredWidth(80);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 150, 875, 350);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel3.setText("Registros :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 6, 72, 16);

        lbl_nroreg.setBackground(java.awt.Color.white);
        lbl_nroreg.setEditable(false);
        lbl_nroreg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lbl_nroreg.setText("0");
        jPanel2.add(lbl_nroreg);
        lbl_nroreg.setBounds(110, 4, 60, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 517, 893, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            ArrayList lista=new ArrayList();
            Reportes re=new Reportes();
            Globales glo=new Globales();
            String id_codper=glo.getId_codper();
            SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
            String f_fecpro;
            
            f_fecpro=sdf.format(dtp_fproceso.getValue()) + " 00:00:00.000";            
            
            lista=re.reporte_impresion_cartas2(f_fecpro,txtc_nrodoc.getText().trim(),txtc_nomcont.getText(),id_codper);
            lbl_nroreg.setText(lista.size() + "");
            
            DefaultTableModel m=(DefaultTableModel)jTable1.getModel();
            m.setRowCount(lista.size());

            for(int i=0;i<lista.size();i++){
              re=(Reportes)lista.get(i);
              m.setValueAt(re.getC_codcent(), i, 0);
              m.setValueAt(re.getC_nrodoc(), i, 1);
              m.setValueAt(re.getC_nombre(), i, 2);
              m.setValueAt(re.getC_direccion(), i, 3);
              m.setValueAt(re.getC_distprov(), i, 4);
              m.setValueAt(re.getMax_diasvenc(), i, 5);
              m.setValueAt(re.getDireccion_encontrada(), i, 6);
              m.setValueAt(re.getDistrito_encontrado(), i, 7);

              m.setValueAt(re.getC_contrato_1(), i, 8);
              m.setValueAt(re.getC_dessubpro_1(), i, 9);
              m.setValueAt(re.getC_nomsubpro_1(), i, 10);
              m.setValueAt(re.getC_divisa_1(), i, 11);
              m.setValueAt(re.getN_saldohoy_1(), i, 12);
              m.setValueAt(re.getN_diasvenc_1(), i, 13);                        
              
              m.setValueAt(re.getC_contrato_2(), i, 14);
              m.setValueAt(re.getC_dessubpro_2(), i, 15);
              m.setValueAt(re.getC_nomsubpro_2(), i, 16);
              m.setValueAt(re.getC_divisa_2(), i, 17);
              m.setValueAt(re.getN_saldohoy_2(), i, 18);
              m.setValueAt(re.getN_diasvenc_2(), i, 19);
                            
              m.setValueAt(re.getC_contrato_3(), i, 20);
              m.setValueAt(re.getC_dessubpro_3(), i, 21);
              m.setValueAt(re.getC_nomsubpro_3(), i, 22);
              m.setValueAt(re.getC_divisa_3(), i, 23);
              m.setValueAt(re.getN_saldohoy_3(), i, 24);
              m.setValueAt(re.getN_diasvenc_3(), i, 25);
              
              m.setValueAt(re.getC_contrato_4(), i, 26);
              m.setValueAt(re.getC_dessubpro_4(), i, 27);
              m.setValueAt(re.getC_nomsubpro_4(), i, 28);
              m.setValueAt(re.getC_divisa_4(), i, 29);
              m.setValueAt(re.getN_saldohoy_4(), i, 30);
              m.setValueAt(re.getN_diasvenc_4(), i, 31);
              
              m.setValueAt(re.getC_contrato_5(), i, 32);
              m.setValueAt(re.getC_dessubpro_5(), i, 33);
              m.setValueAt(re.getC_nomsubpro_5(), i, 34);
              m.setValueAt(re.getC_divisa_5(), i, 35);
              m.setValueAt(re.getN_saldohoy_5(), i, 36);
              m.setValueAt(re.getN_diasvenc_5(), i, 37);
              
              m.setValueAt(re.getC_contrato_6(), i, 38);
              m.setValueAt(re.getC_dessubpro_6(), i, 39);
              m.setValueAt(re.getC_nomsubpro_6(), i, 40);
              m.setValueAt(re.getC_divisa_6(), i, 41);
              m.setValueAt(re.getN_saldohoy_6(), i, 42);
              m.setValueAt(re.getN_diasvenc_6(), i, 43);

              if(re.getF_fecimp_ult()!=null){
              m.setValueAt(String.valueOf(re.getF_fecimp_ult()).substring(8, 10) + "/" +
              String.valueOf(re.getF_fecimp_ult()).substring(5, 7) + "/" + 
              String.valueOf(re.getF_fecimp_ult()).substring(0, 4), i, 44);
              }else{
               m.setValueAt(re.getF_fecimp_ult(), i, 44);
              }

              m.setValueAt(re.getC_codrspta(), i, 45);
              m.setValueAt(re.getC_desrspta_sub(), i, 46);

              if(re.getF_fproceso()!=null){
              m.setValueAt(String.valueOf(re.getF_fproceso()).substring(8, 10) + "/" +
              String.valueOf(re.getF_fproceso()).substring(5, 7) + "/" +
              String.valueOf(re.getF_fproceso()).substring(0, 4), i, 47);
              }else{
               m.setValueAt(re.getF_fproceso(), i, 47);
              }

              m.setValueAt(re.getC_destcon(), i, 48);
              m.setValueAt(re.getC_destres(), i, 49);
              m.setValueAt(re.getC_cuad_plano(), i, 50);
              m.setValueAt(re.getC_cuad_x(), i, 51);
              m.setValueAt(re.getC_cuad_y(), i, 52);
              
            }jTable1.setModel(m);

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            JFileChooser caja=new JFileChooser();
            caja.showSaveDialog(null);
            File arch=caja.getSelectedFile();

            if(arch==null){
                return;
            }

            DataOutputStream out=new DataOutputStream(new FileOutputStream(arch + ".xls"));
            WritableWorkbook w = Workbook.createWorkbook(out);
            WritableSheet s = w.createSheet("reporte", 0);
            WritableFont headersfont=new WritableFont(WritableFont.ARIAL, 10, WritableFont.BOLD, false, UnderlineStyle.NO_UNDERLINE, Colour.WHITE);
            WritableCellFormat headersformat=new WritableCellFormat(headersfont);
            headersformat.setBackground(Colour.ORANGE);

            s.addCell(new Label(0, 0, String.valueOf("c_codcent"),headersformat));
            s.addCell(new Label(1, 0, String.valueOf("c_nrodoc"),headersformat));
            s.addCell(new Label(2, 0, String.valueOf("c_nombre"),headersformat));
            s.addCell(new Label(3, 0, String.valueOf("c_direccion"),headersformat));
            s.addCell(new Label(4, 0, String.valueOf("c_distprov"),headersformat));
            s.addCell(new Label(5, 0, String.valueOf("max_diasvenc"),headersformat));
            s.addCell(new Label(6, 0, String.valueOf("direccion_encontrada"),headersformat));
            s.addCell(new Label(7, 0, String.valueOf("distrito_encontrado"),headersformat));
            s.addCell(new Label(8, 0, String.valueOf("c_contrato_1"),headersformat));
            s.addCell(new Label(9, 0, String.valueOf("c_dessubpro_1"),headersformat));
            s.addCell(new Label(10, 0, String.valueOf("c_nomsubpro_1"),headersformat));
            s.addCell(new Label(11, 0, String.valueOf("c_divisa_1"),headersformat));
            s.addCell(new Label(12, 0, String.valueOf("n_saldohoy_1"),headersformat));
            s.addCell(new Label(13, 0, String.valueOf("n_diasvenc_1"),headersformat));

            s.addCell(new Label(14, 0, String.valueOf("c_contrato_2"),headersformat));
            s.addCell(new Label(15, 0, String.valueOf("c_dessubpro_2"),headersformat));
            s.addCell(new Label(16, 0, String.valueOf("c_nomsubpro_2"),headersformat));
            s.addCell(new Label(17, 0, String.valueOf("c_divisa_2"),headersformat));
            s.addCell(new Label(18, 0, String.valueOf("n_saldohoy_2"),headersformat));
            s.addCell(new Label(19, 0, String.valueOf("n_diasvenc_2"),headersformat));

            s.addCell(new Label(20, 0, String.valueOf("c_contrato_3"),headersformat));
            s.addCell(new Label(21, 0, String.valueOf("c_dessubpro_3"),headersformat));
            s.addCell(new Label(22, 0, String.valueOf("c_nomsubpro_3"),headersformat));
            s.addCell(new Label(23, 0, String.valueOf("c_divisa_3"),headersformat));
            s.addCell(new Label(24, 0, String.valueOf("n_saldohoy_3"),headersformat));
            s.addCell(new Label(25, 0, String.valueOf("n_diasvenc_3"),headersformat));

            s.addCell(new Label(26, 0, String.valueOf("c_contrato_4"),headersformat));
            s.addCell(new Label(27, 0, String.valueOf("c_dessubpro_4"),headersformat));
            s.addCell(new Label(28, 0, String.valueOf("c_nomsubpro_4"),headersformat));
            s.addCell(new Label(29, 0, String.valueOf("c_divisa_4"),headersformat));
            s.addCell(new Label(30, 0, String.valueOf("n_saldohoy_4"),headersformat));
            s.addCell(new Label(31, 0, String.valueOf("n_diasvenc_4"),headersformat));

            s.addCell(new Label(32, 0, String.valueOf("c_contrato_5"),headersformat));
            s.addCell(new Label(33, 0, String.valueOf("c_dessubpro_5"),headersformat));
            s.addCell(new Label(34, 0, String.valueOf("c_nomsubpro_5"),headersformat));
            s.addCell(new Label(35, 0, String.valueOf("c_divisa_5"),headersformat));
            s.addCell(new Label(36, 0, String.valueOf("n_saldohoy_5"),headersformat));
            s.addCell(new Label(37, 0, String.valueOf("n_diasvenc_5"),headersformat));

            s.addCell(new Label(38, 0, String.valueOf("c_contrato_6"),headersformat));
            s.addCell(new Label(39, 0, String.valueOf("c_dessubpro_6"),headersformat));
            s.addCell(new Label(40, 0, String.valueOf("c_nomsubpro_6"),headersformat));
            s.addCell(new Label(41, 0, String.valueOf("c_divisa_6"),headersformat));
            s.addCell(new Label(42, 0, String.valueOf("n_saldohoy_6"),headersformat));
            s.addCell(new Label(43, 0, String.valueOf("n_diasvenc_6"),headersformat));

            s.addCell(new Label(44, 0, String.valueOf("f_fecimp_ult"),headersformat));
            s.addCell(new Label(45, 0, String.valueOf("c_codrspta"),headersformat));
            s.addCell(new Label(46, 0, String.valueOf("c_desrspta_sub"),headersformat));
            s.addCell(new Label(47, 0, String.valueOf("f_fproceso"),headersformat));
            s.addCell(new Label(48, 0, String.valueOf("c_destcon"),headersformat));
            s.addCell(new Label(49, 0, String.valueOf("c_destres"),headersformat));
            s.addCell(new Label(50, 0, String.valueOf("Cuad_plano"),headersformat));
            s.addCell(new Label(51, 0, String.valueOf("Cuad_x"),headersformat));
            s.addCell(new Label(52, 0, String.valueOf("Cuad_y"),headersformat));

           
            for(int i=0;i<jTable1.getRowCount();i++){

              for(int j=0;j<jTable1.getColumnCount();j++){
                 Object objeto=jTable1.getValueAt(i,j);
                 if(objeto!=null){
                    if(j==5 || j==13 || j==19 || j==25 || j==31 || j==37 || j==43){
                      s.addCell(new jxl.write.Number(j, i+1, Integer.parseInt(objeto + "")));
                    }else{
                      s.addCell(new Label(j, i+1, String.valueOf(objeto)));
                    }
                 }else{
                   s.addCell(new Label(j, i+1, ""));
                 }
               }
            }

            w.write();
            w.close();
            out.close();

            JOptionPane.showMessageDialog(null,"Reporte Terminado");
            
        }catch(Exception ioE){
            JOptionPane.showMessageDialog(null, ioE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner dtp_fproceso;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField lbl_nroreg;
    private javax.swing.JTextField txtc_nomcont;
    private javax.swing.JTextField txtc_nrodoc;
    // End of variables declaration//GEN-END:variables

}
