

package FORMULARIOS;

import BEANS.Cartera;
import BEANS.Globales;
import java.awt.Rectangle;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jxl.Workbook;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.Label;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
//import org.jvnet.substance.SubstanceLookAndFeel;

public class frm_importar_car extends javax.swing.JDialog {

    public File arch;

    public frm_importar_car(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();      
        frm_importar_car.setDefaultLookAndFeelDecorated(true);
      //  SubstanceLookAndFe.setSkin("org.jvnet.substance.skin.DustCoffeeSkin");

        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        btn_importar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_ruta = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Importar cartera");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EXPENSES.GIF"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 140, 140);

        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("Esta Opcion Permite Importar Datos de Contacto desde");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(165, 10, 320, 20);

        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setText(" una Hoja de Excel");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(165, 30, 140, 18);

        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("Seleccione Hoja de Calculo :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(165, 60, 210, 18);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/open.JPG"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 50, 30, 30);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(3, 108, 252));
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(160, 130, 320, 22);

        btn_importar.setText("Importar");
        btn_importar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_importar);
        btn_importar.setBounds(390, 160, 90, 30);

        lbl_ruta.setBackground(javax.swing.UIManager.getDefaults().getColor("Label.background"));
        lbl_ruta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_ruta.setEditable(false);
        lbl_ruta.setForeground(java.awt.Color.blue);
        jScrollPane1.setViewportView(lbl_ruta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(160, 80, 280, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(5, 5, 490, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String ruta;
        JFileChooser caja=new JFileChooser();
        caja.showOpenDialog(null);
        arch=caja.getSelectedFile();

        if(arch==null){
        return;
        }

        ruta=arch.getPath();
        lbl_ruta.setText(ruta);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_importarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importarActionPerformed
       
      try{          

       if(lbl_ruta.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Seleccione Archivo a importar");
        return;
       }

        int i=0;        

        Cartera car=new Cartera();
        Globales glo=new Globales();        
        String sCadena="";
        String sCadena2="";
        FileReader f = new FileReader(arch);
        FileReader fr = new FileReader(arch);
        BufferedReader b = new BufferedReader(f);
        BufferedReader bf = new BufferedReader(fr);

        int lNumeroLineas = 0;

        while ((sCadena = b.readLine())!=null) {
         lNumeroLineas++;
        }
        
        
        DecimalFormat dc=new DecimalFormat("##########.##");
        DateFormat df=new SimpleDateFormat("dd-MMM-yy", Locale.UK);
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");

        jProgressBar1.setMaximum(lNumeroLineas);
        jProgressBar1.setMinimum(0);

       String proceso,f_fproceso="",c_agencia, c_gestor, c_territorio, c_oficina, c_subprod, c_nomsubpro, c_contrato,
       c_codcent, c_tpersona, c_nombre, c_divisa, c_direccion, c_telefono, c_codpostal, c_codestado,
       c_codprov, c_coddist, f_fincumpli, c_ubigeo, c_dpto, c_distprov, c_tramodia, c_tipodoc, c_nrodoc,
       c_tipofono1, c_prefijo1, c_fono1, c_extension1, c_tipofono2, c_prefijo2, c_fono2, c_extension2,
       c_tipofono3, c_prefijo3, c_fono3, c_extension3, c_tipofono4, c_prefijo4, c_fono4, c_extension4,
       c_tipofono5, c_prefijo5, c_fono5, c_extension5, c_email, c_dessubpro;

       Float n_saldohoy;
       int n_diasvenc;

       car.eliminar_data();
      
       while ((sCadena = bf.readLine())!=null) {

        jProgressBar1.setValue(i);
        jProgressBar1.setStringPainted(true);
        Rectangle progreso=jProgressBar1.getBounds();
        progreso.x=0;
        progreso.y=0;
        jProgressBar1.paintImmediately(progreso);      
     
      
//      Date fecha;
//      fecha=df.parse(sCadena.substring(0, 9));
//      f_fproceso= "'" + sdf.format(fecha) + "'";
//
//      c_agencia= "'" + sCadena.substring(9,50).trim() + "'";    //'c_agencia'
//      c_gestor= "'" + sCadena.substring(59,100).trim() + "'";   // 'c_gestor',
//      c_territorio= "'" + sCadena.substring(159,199).trim() + "'";  //  'c_territorio',
//      c_oficina= "'" + sCadena.substring(199,203).trim() + "'";    // 'c_oficina',
//      c_subprod= "'" + sCadena.substring(203,207).trim() + "'";    // 'c_subprod',
//      c_dessubpro= "'" + sCadena.substring(207,257).trim() + "'";  // 'c_dessubpro',
//      c_contrato= "'" + sCadena.substring(257,275).trim() + "'";  // 'c_contrato',
//      c_codcent= "'" + sCadena.substring(275,283).trim() + "'";  // 'c_codcent',
//      c_tpersona= "'" + sCadena.substring(283,286).trim() + "'";  //  'c_tpersona',
//      c_nombre= "'" + sCadena.substring(286,336).trim().replace("'", " ") + "'";  // 'c_nombre',
//      c_divisa= "'" + sCadena.substring(336,339).trim() + "'";  // 'c_divisa',
//      n_saldohoy=Float.parseFloat(sCadena.substring(339,354))/100;
//
//      if(sCadena.substring(354,404).trim().length()>0){
//      c_direccion= "'" + sCadena.substring(354,404).trim().replace("'", " ") + "'";  //  'c_direccion',
//      }else{
//      c_direccion=null;
//      }
//
//      if(sCadena.substring(404,413).trim().length()>0){
//       c_telefono= "'" + sCadena.substring(404,413).trim() + "'";  // 'c_telefono',
//      }else{
//       c_telefono= null;  // 'c_telefono',
//      }
//
//      if(sCadena.substring(413,418).trim().length()>0){
//       c_codpostal= "'" + sCadena.substring(413,418).trim() + "'";  //  'c_codpostal',
//      }else{
//       c_codpostal=null;
//      }
//
//      if(sCadena.substring(418,420).trim().length()>0){
//       c_codestado= "'" + sCadena.substring(418,420).trim() + "'";  // 'c_codestado',
//      }else{
//       c_codestado=null;
//      }
//
//      if(sCadena.substring(420,422).trim().length()>0){
//       c_codprov= "'" + sCadena.substring(420,422).trim() + "'";   // 'c_codprov',
//      }else{
//       c_codprov=null;
//      }
//
//
//      if(sCadena.substring(422,425).trim().length()>0){
//       c_coddist= "'" + sCadena.substring(422,425).trim() + "'";   // 'c_coddist',
//      }else{
//       c_coddist=null;   // 'c_coddist',
//      }
//
//
//      f_fincumpli= "'" + sCadena.substring(425,435).trim() + "'";
//      n_diasvenc=Integer.parseInt(sCadena.substring(435,440).trim());
//
//
//      if(sCadena.substring(440,470).trim().length()>0){
//       c_ubigeo= "'" + sCadena.substring(440,470).trim() + "'";   // 'c_ubigeo',
//      }else{
//       c_ubigeo=null;   // 'c_ubigeo',
//      }
//
//      if(sCadena.substring(470,500).trim().length()>0){
//       c_dpto= "'" + sCadena.substring(470,500).trim() + "'";   // 'c_dpto',
//      }else{
//       c_dpto=null;   // 'c_dpto',
//      }
//
//      if(sCadena.substring(500,530).trim().length()>0){
//       c_distprov= "'" + sCadena.substring(500,530).trim() + "'";   // 'c_distprov',
//      }else{
//       c_distprov=null;
//      }
//
//
//      if(sCadena.substring(530,544).trim().length()>0){
//       c_tramodia= "'" + sCadena.substring(530,544).trim() + "'";   //'c_tramodia',
//      }else{
//       c_tramodia=null;   //'c_tramodia',
//      }
//
//      if(sCadena.substring(544,546).trim().length()>0){
//       c_tipodoc= "'" + sCadena.substring(544,546).trim() + "'";  //'c_tipodoc',
//      }else{
//       c_tipodoc=null;  //'c_tipodoc',
//      }
//
//
//      if(c_tipodoc.equals("L")){
//       c_nrodoc= "'" + (sCadena.substring(546,561)).substring(0, 8).trim() + "'";
//      }else{
//       c_nrodoc= "'" + sCadena.substring(546,561).trim() + "'";
//      }
//
//
//      if(sCadena.substring(562,565).trim().length()>0){
//       c_tipofono1= "'" + sCadena.substring(561,564).trim() + "'";    // 'c_tipofono1',
//      }else{
//       c_tipofono1=null;   // 'c_tipofono1',
//      }
//
//
//      if(sCadena.substring(565,568).trim().length()>0){
//       c_prefijo1= "'" + sCadena.substring(564,567).trim() + "'";   // 'c_prefijo1',
//      }else{
//       c_prefijo1= null;   // 'c_prefijo1',
//      }
//
//
//      if(sCadena.substring(567,577).trim().length()>0){
//       c_fono1= "'" + sCadena.substring(567,577).trim() + "'";   // 'c_fono1',
//      }else{
//       c_fono1=null;
//      }
//
//
//      if(sCadena.substring(577,581).trim().length()>0){
//       c_extension1= "'" + sCadena.substring(577,581).trim() + "'";   // 'c_extension1',
//      }else{
//       c_extension1=null;
//      }
//
//
//      if(sCadena.substring(581,584).trim().length()>0){
//       c_tipofono2= "'" + sCadena.substring(581,584).trim() + "'"; //  'c_tipofono2',
//      }else{
//       c_tipofono2=null; //  'c_tipofono2',
//      }
//
//
//      if(sCadena.substring(584,587).trim().length()>0){
//       c_prefijo2= "'" + sCadena.substring(584,587).trim() + "'"; //  'c_prefijo2',
//      }else{
//       c_prefijo2=null;
//      }
//
//
//      if(sCadena.substring(587,597).trim().length()>0){
//       c_fono2= "'" + sCadena.substring(587,597).trim() + "'"; //  'c_fono2',
//      }else{
//       c_fono2=null;
//      }
//
//      if(sCadena.substring(597,601).trim().length()>0){
//       c_extension2= "'" + sCadena.substring(597,601).trim() + "'";   // 'c_extension2',
//      }else{
//       c_extension2=null;   // 'c_extension2',
//      }
//
//      if(sCadena.substring(601,604).trim().length()>0){
//       c_tipofono3= "'" + sCadena.substring(601,604).trim() + "'";  // 'c_tipofono3',
//      }else{
//       c_tipofono3=null;  // 'c_tipofono3',
//      }
//
//      if(sCadena.substring(604,607).trim().length()>0){
//       c_prefijo3= "'" + sCadena.substring(604,607).trim() + "'";  // 'c_prefijo3',
//      }else{
//       c_prefijo3=null;  // 'c_prefijo3',
//      }
//
//
//      if(sCadena.substring(607,617).trim().length()>0){
//       c_fono3= "'" + sCadena.substring(607,617).trim() + "'"; // 'c_fono3',
//      }else{
//       c_fono3=null; // 'c_fono3',
//      }
//
//      if(sCadena.substring(617,621).trim().length()>0){
//       c_extension3= "'" + sCadena.substring(617,621).trim() + "'";   // 'c_extension3',
//      }else{
//       c_extension3=null;   // 'c_extension3',
//      }
//
//      if(sCadena.substring(621,624).trim().length()>0){
//       c_tipofono4= "'" + sCadena.substring(621,624).trim() + "'";  //  'c_tipofono4',
//      }else{
//       c_tipofono4=null;
//      }
//
//      if(sCadena.substring(624,627).trim().length()>0){
//       c_prefijo4= "'" + sCadena.substring(624,627).trim() + "'";   // 'c_prefijo4',
//      }else{
//       c_prefijo4=null;
//      }
//
//
//      if(sCadena.substring(627,637).trim().length()>0){
//       c_fono4= "'" + sCadena.substring(627,637).trim() + "'";  //  'c_fono4',
//      }else{
//       c_fono4=null;
//      }
//
//
//      if(sCadena.substring(637,641).trim().length()>0){
//       c_extension4= "'" + sCadena.substring(637,641).trim() + "'";  //  'c_extension4',
//      }else{
//       c_extension4=null;
//      }
//
//
//      if(sCadena.substring(641,644).trim().length()>0){
//       c_tipofono5= "'" + sCadena.substring(641,644).trim() + "'";  // 'c_tipofono5',
//      }else{
//       c_tipofono5=null;
//      }
//
//      if(sCadena.substring(644,647).trim().length()>0){
//       c_prefijo5= "'" + sCadena.substring(644,647).trim() + "'";  // 'c_prefijo5',
//      }else{
//       c_prefijo5=null;
//      }
//
//
//      if(sCadena.substring(647,657).trim().length()>0){
//       c_fono5= "'" + sCadena.substring(647,657).trim() + "'";  //  'c_fono5',
//      }else{
//       c_fono5=null;
//      }
//
//      if(sCadena.substring(657,661).trim().length()>0){
//       c_extension5= "'" + sCadena.substring(657,661).trim() + "'";   // 'c_extension5',
//      }else{
//       c_extension5=null;
//      }
//
//      if(sCadena.substring(661,701).trim().length()>0){
//       c_email= "'" + sCadena.substring(661,701).trim().replace("'", " ") + "'";   // 'c_email',
//      }else{
//       c_email=null;
//      }
//
//      if(sCadena.substring(843,858).trim().length()>0){
//      c_nomsubpro= "'" + sCadena.substring(843,858).trim() + "'";
//      }else{
//      c_nomsubpro=null;
//      }
//
//      car.migrar_cartera(f_fproceso, c_agencia, c_gestor, c_territorio, c_oficina,
//      c_subprod, c_nomsubpro, c_contrato, c_codcent, c_tpersona, c_nombre,
//      c_divisa, n_saldohoy, c_direccion, c_telefono, c_codpostal, c_codestado,
//      c_codprov, c_coddist, f_fincumpli, n_diasvenc, c_ubigeo, c_dpto,
//      c_distprov, c_tramodia, c_tipodoc, c_nrodoc, c_tipofono1, c_prefijo1,
//      c_fono1, c_extension1, c_tipofono2, c_prefijo2, c_fono2, c_extension2,
//      c_tipofono3, c_prefijo3, c_fono3, c_extension3, c_tipofono4, c_prefijo4,
//      c_fono4, c_extension4, c_tipofono5, c_prefijo5, c_fono5, c_extension5,
//      c_email, null, null, 0.00, 0.00, 0.00, c_dessubpro, c_oficina, null, null, null, null,
//      null, null, null, "'" + glo.getId_codper() + "'");

      car.migrar_cartera(sCadena);

      i=i+1;

      }jProgressBar1.setValue(i);
       JOptionPane.showMessageDialog(null,"Migracion Finalizada");
       jProgressBar1.setValue(0);

        JFileChooser caja2=new JFileChooser();
        caja2.showSaveDialog(null);
        File arch2=caja2.getSelectedFile();

        if(arch2==null){
        return;
        }

        DataOutputStream out=new DataOutputStream(new FileOutputStream(arch2 + ".xls"));
        WritableWorkbook w = Workbook.createWorkbook(out);
        WritableSheet s = w.createSheet("reporte", 0);
        WritableFont headersfont=new WritableFont(WritableFont.ARIAL, 10, WritableFont.BOLD, false, UnderlineStyle.NO_UNDERLINE, Colour.WHITE);
        WritableCellFormat headersformat=new WritableCellFormat(headersfont);
        headersformat.setBackground(Colour.ORANGE);

         s.addCell(new Label(0, 0, String.valueOf("if_fproceso"),headersformat));
         s.addCell(new Label(1, 0, String.valueOf("ic_agencia"),headersformat));
         s.addCell(new Label(2, 0, String.valueOf("ic_gestor"),headersformat));
         s.addCell(new Label(3, 0, String.valueOf("ic_territorio"),headersformat));
         s.addCell(new Label(4, 0, String.valueOf("ic_oficina"),headersformat));
         s.addCell(new Label(5, 0, String.valueOf("ic_subprod"),headersformat));
         s.addCell(new Label(6, 0, String.valueOf("ic_nomsubpro"),headersformat));
         s.addCell(new Label(7, 0, String.valueOf("ic_contrato"),headersformat));
         s.addCell(new Label(8, 0, String.valueOf("ic_codcent"),headersformat));
         s.addCell(new Label(9, 0, String.valueOf("ic_tpersona"),headersformat));
         s.addCell(new Label(10, 0, String.valueOf("ic_nombre"),headersformat));
         s.addCell(new Label(11, 0, String.valueOf("ic_divisa"),headersformat));
         s.addCell(new Label(12, 0, String.valueOf("in_saldohoy"),headersformat));
         s.addCell(new Label(13, 0, String.valueOf("ic_direccion"),headersformat));
         s.addCell(new Label(14, 0, String.valueOf("ic_telefono"),headersformat));
         s.addCell(new Label(15, 0, String.valueOf("ic_codpostal"),headersformat));
         s.addCell(new Label(16, 0, String.valueOf("ic_codestado"),headersformat));
         s.addCell(new Label(17, 0, String.valueOf("ic_codprov"),headersformat));
         s.addCell(new Label(18, 0, String.valueOf("ic_coddist"),headersformat));
         s.addCell(new Label(19, 0, String.valueOf("if_fincumpli"),headersformat));
         s.addCell(new Label(20, 0, String.valueOf("in_diasvenc"),headersformat));
         s.addCell(new Label(21, 0, String.valueOf("ic_ubigeo"),headersformat));
         s.addCell(new Label(22, 0, String.valueOf("ic_dpto"),headersformat));
         s.addCell(new Label(23, 0, String.valueOf("ic_distprov"),headersformat));
         s.addCell(new Label(24, 0, String.valueOf("ic_tramodia"),headersformat));
         s.addCell(new Label(25, 0, String.valueOf("ic_tipodoc"),headersformat));
         s.addCell(new Label(26, 0, String.valueOf("ic_nrodoc"),headersformat));
         s.addCell(new Label(27, 0, String.valueOf("ic_tipofono1"),headersformat));
         s.addCell(new Label(28, 0, String.valueOf("ic_prefijo1"),headersformat));
         s.addCell(new Label(29, 0, String.valueOf("ic_fono1"),headersformat));
         s.addCell(new Label(30, 0, String.valueOf("ic_extension1"),headersformat));
         s.addCell(new Label(31, 0, String.valueOf("ic_tipofono2"),headersformat));
         s.addCell(new Label(32, 0, String.valueOf("ic_prefijo2"),headersformat));
         s.addCell(new Label(33, 0, String.valueOf("ic_fono2"),headersformat));
         s.addCell(new Label(34, 0, String.valueOf("ic_extension2"),headersformat));
         s.addCell(new Label(35, 0, String.valueOf("ic_tipofono3"),headersformat));
         s.addCell(new Label(36, 0, String.valueOf("ic_prefijo3"),headersformat));
         s.addCell(new Label(37, 0, String.valueOf("ic_fono3"),headersformat));
         s.addCell(new Label(38, 0, String.valueOf("ic_extension3"),headersformat));
         s.addCell(new Label(39, 0, String.valueOf("ic_distprov"),headersformat));
         s.addCell(new Label(40, 0, String.valueOf("ic_tipofono4"),headersformat));
         s.addCell(new Label(41, 0, String.valueOf("ic_prefijo4"),headersformat));
         s.addCell(new Label(42, 0, String.valueOf("ic_fono4"),headersformat));
         s.addCell(new Label(43, 0, String.valueOf("ic_extension4"),headersformat));
         s.addCell(new Label(44, 0, String.valueOf("ic_tipofono5"),headersformat));
         s.addCell(new Label(45, 0, String.valueOf("ic_prefijo5"),headersformat));
         s.addCell(new Label(46, 0, String.valueOf("ic_fono5"),headersformat));
         s.addCell(new Label(47, 0, String.valueOf("ic_extension5"),headersformat));
         s.addCell(new Label(48, 0, String.valueOf("ic_email"),headersformat));
         s.addCell(new Label(49, 0, String.valueOf("if_fecha_generacion_registro"),headersformat));
         s.addCell(new Label(50, 0, String.valueOf("if_fecha_ingreso"),headersformat));
         s.addCell(new Label(51, 0, String.valueOf("ic_oficina2"),headersformat));
         s.addCell(new Label(52, 0, String.valueOf("ic_producto"),headersformat));
         s.addCell(new Label(53, 0, String.valueOf("ic_marca"),headersformat));
         s.addCell(new Label(54, 0, String.valueOf("ic_tipo_telefono1"),headersformat));
         s.addCell(new Label(55, 0, String.valueOf("ic_prefijo_telefono1"),headersformat));
         s.addCell(new Label(56, 0, String.valueOf("ic_telefono1"),headersformat));
         s.addCell(new Label(57, 0, String.valueOf("ic_extencion1"),headersformat));
         s.addCell(new Label(58, 0, String.valueOf("ic_tipo_telefono2"),headersformat));
         s.addCell(new Label(59, 0, String.valueOf("ic_prefijo_telefono2"),headersformat));
         s.addCell(new Label(60, 0, String.valueOf("ic_telefono2"),headersformat));
         s.addCell(new Label(61, 0, String.valueOf("ic_extencion2"),headersformat));
         s.addCell(new Label(62, 0, String.valueOf("ic_direccion1"),headersformat));
         s.addCell(new Label(63, 0, String.valueOf("ic_departamento1"),headersformat));
         s.addCell(new Label(64, 0, String.valueOf("ic_provincia1"),headersformat));
         s.addCell(new Label(65, 0, String.valueOf("ic_distrito1"),headersformat));
         s.addCell(new Label(66, 0, String.valueOf("ic_direccion2"),headersformat));
         s.addCell(new Label(67, 0, String.valueOf("ic_departamento2"),headersformat));
         s.addCell(new Label(68, 0, String.valueOf("ic_provincia2"),headersformat));
         s.addCell(new Label(69, 0, String.valueOf("ic_distrito2"),headersformat));
         s.addCell(new Label(70, 0, String.valueOf("if_ult_fecasig"),headersformat));
         s.addCell(new Label(71, 0, String.valueOf("ic_ult_id_codtcon"),headersformat));
         s.addCell(new Label(72, 0, String.valueOf("ic_ult_c_destcon"),headersformat));
         s.addCell(new Label(73, 0, String.valueOf("ic_ult_id_codtres"),headersformat));
         s.addCell(new Label(74, 0, String.valueOf("ic_ult_c_destres"),headersformat));
         s.addCell(new Label(75, 0, String.valueOf("if_ult_fecresp"),headersformat));
         s.addCell(new Label(76, 0, String.valueOf("ic_ult_id_codusu"),headersformat));
         s.addCell(new Label(77, 0, String.valueOf("ic_ult_c_nomusu"),headersformat));
         s.addCell(new Label(78, 0, String.valueOf("in_return"),headersformat));


         ArrayList lista=new ArrayList();
         lista=car.lista_reporte_cartera(glo.getId_codper());

         for(int j=0;j<lista.size();j++){
         car=(Cartera)lista.get(j);

         s.addCell(new Label(0, j+1, String.valueOf(car.getF_fproceso()).substring(8, 10) + "/" +
         String.valueOf(car.getF_fproceso()).substring(5, 7) + "/" +
         String.valueOf(car.getF_fproceso()).substring(0, 4)));

         s.addCell(new Label(1, j+1, String.valueOf(car.getC_agencia())));
         s.addCell(new Label(2, j+1, String.valueOf(car.getC_gestor())));
         s.addCell(new Label(3, j+1, String.valueOf(car.getC_territorio())));
         s.addCell(new Label(4, j+1, String.valueOf(car.getC_oficina())));
         s.addCell(new Label(5, j+1, String.valueOf(car.getC_subprod())));
         s.addCell(new Label(6, j+1, String.valueOf(car.getC_nomsubpro())));
         s.addCell(new Label(7, j+1, String.valueOf(car.getC_contrato())));
         s.addCell(new Label(8, j+1, String.valueOf(car.getC_codcent())));

         if(car.getC_tpersona()!=null){
          s.addCell(new Label(9, j+1, String.valueOf(car.getC_tpersona())));
         }else{
          s.addCell(new Label(9, j+1, ""));
         }

         s.addCell(new Label(10, j+1, String.valueOf(car.getC_nombre())));
         s.addCell(new Label(11, j+1, String.valueOf(car.getC_divisa())));
         s.addCell(new Label(12, j+1, String.valueOf(car.getN_saldohoy2())));

         if(car.getC_direccion()!=null){
          s.addCell(new Label(13, j+1, String.valueOf(car.getC_direccion())));
         }else{
          s.addCell(new Label(13, j+1, ""));
         }

         if(car.getC_telefono()!=null){
          s.addCell(new Label(14, j+1, String.valueOf(car.getC_telefono())));
         }else{
          s.addCell(new Label(14, j+1, ""));
         }

         if(car.getC_codpostal()!=null){
          s.addCell(new Label(15, j+1, String.valueOf(car.getC_codpostal())));
         }else{
          s.addCell(new Label(15, j+1, ""));
         }

         if(car.getC_codestado()!=null){
          s.addCell(new Label(16, j+1, String.valueOf(car.getC_codestado())));
         }else{
          s.addCell(new Label(16, j+1, ""));
         }

         if(car.getC_codprov()!=null){
          s.addCell(new Label(17, j+1, String.valueOf(car.getC_codprov())));
         }else{
          s.addCell(new Label(17, j+1, ""));
         }

         if(car.getC_coddist()!=null){
          s.addCell(new Label(18, j+1, String.valueOf(car.getC_coddist())));
         }else{
          s.addCell(new Label(18, j+1, ""));
         }

         if(car.getF_fincumpli()!=null){
          s.addCell(new Label(19, j+1, String.valueOf(String.valueOf(car.getF_fincumpli()).substring(8, 10) + "/" +
          String.valueOf(car.getF_fincumpli()).substring(5, 7) + "/" +
          String.valueOf(car.getF_fincumpli()).substring(0, 4))));
         }else{
          s.addCell(new Label(19, j+1, ""));
         }

         if(car.getN_diasvenc2()!=null){
          s.addCell(new jxl.write.Number(20, j+1, Integer.parseInt(car.getN_diasvenc2())));
         }else{
          s.addCell(new Label(20, j+1, ""));
         }

         if(car.getC_ubigeo()!=null){
          s.addCell(new Label(21, j+1, String.valueOf(car.getC_ubigeo())));
         }else{
          s.addCell(new Label(21, j+1, ""));
         }

         if(car.getC_dpto()!=null){
          s.addCell(new Label(22, j+1, String.valueOf(car.getC_dpto())));
         }else{
          s.addCell(new Label(22, j+1, ""));
         }

         if(car.getC_distprov()!=null){
          s.addCell(new Label(23, j+1, String.valueOf(car.getC_distprov())));
         }else{
          s.addCell(new Label(23, j+1, ""));
         }

         if(car.getC_tramodia()!=null){
          s.addCell(new Label(24, j+1, String.valueOf(car.getC_tramodia())));
         }else{
          s.addCell(new Label(24, j+1, ""));
         }

         if(car.getC_tipodoc()!=null){
          s.addCell(new Label(25, j+1, String.valueOf(car.getC_tipodoc())));
         }else{
          s.addCell(new Label(25, j+1, ""));
         }

         if(car.getC_nrodoc()!=null){
          s.addCell(new Label(26, j+1, String.valueOf(car.getC_nrodoc() + "'")));
         }else{
          s.addCell(new Label(26, j+1, ""));
         }

         if(car.getC_tipofono1()!=null){
          s.addCell(new Label(27, j+1, String.valueOf(car.getC_tipofono1())));
         }else{
          s.addCell(new Label(27, j+1, ""));
         }

         if(car.getC_prefijo1()!=null){
          s.addCell(new Label(28, j+1, String.valueOf(car.getC_prefijo1())));
         }else{
          s.addCell(new Label(28, j+1, ""));
         }

         if(car.getC_fono1()!=null){
          s.addCell(new Label(29, j+1, String.valueOf(car.getC_fono1())));
         }else{
          s.addCell(new Label(29, j+1, ""));
         }

         if(car.getC_extension1()!=null){
          s.addCell(new Label(30, j+1, String.valueOf(car.getC_extension1())));
         }else{
          s.addCell(new Label(30, j+1, ""));
         }

         if(car.getC_tipofono2()!=null){
          s.addCell(new Label(31, j+1, String.valueOf(car.getC_tipofono2())));
         }else{
          s.addCell(new Label(31, j+1, ""));
         }

         if(car.getC_prefijo2()!=null){
          s.addCell(new Label(32, j+1, String.valueOf(car.getC_prefijo2())));
         }else{
          s.addCell(new Label(32, j+1, ""));
         }

         if(car.getC_fono2()!=null){
          s.addCell(new Label(33, j+1, String.valueOf(car.getC_fono2())));
         }else{
          s.addCell(new Label(33, j+1, ""));
         }

         if(car.getC_extension2()!=null){
          s.addCell(new Label(34, j+1, String.valueOf(car.getC_extension2())));
         }else{
          s.addCell(new Label(34, j+1, ""));
         }

         if(car.getC_tipofono3()!=null){
          s.addCell(new Label(35, j+1, String.valueOf(car.getC_tipofono3())));
         }else{
          s.addCell(new Label(35, j+1, ""));
         }

         if(car.getC_prefijo3()!=null){
          s.addCell(new Label(36, j+1, String.valueOf(car.getC_prefijo3())));
         }else{
          s.addCell(new Label(36, j+1, ""));
         }

         if(car.getC_fono3()!=null){
          s.addCell(new Label(37, j+1, String.valueOf(car.getC_fono3())));
         }else{
          s.addCell(new Label(37, j+1, ""));
         }

         if(car.getC_extension3()!=null){
          s.addCell(new Label(38, j+1, String.valueOf(car.getC_extension3())));
         }else{
          s.addCell(new Label(38, j+1, ""));
         }

         if(car.getC_distprov()!=null){
          s.addCell(new Label(39, j+1, String.valueOf(car.getC_distprov())));
         }else{
          s.addCell(new Label(39, j+1, ""));
         }

         if(car.getC_tipofono4()!=null){
          s.addCell(new Label(40, j+1, String.valueOf(car.getC_tipofono4())));
         }else{
          s.addCell(new Label(40, j+1, ""));
         }

         if(car.getC_prefijo4()!=null){
          s.addCell(new Label(41, j+1, String.valueOf(car.getC_prefijo4())));
         }else{
          s.addCell(new Label(41, j+1, ""));
         }

         if(car.getC_fono4()!=null){
          s.addCell(new Label(42, j+1, String.valueOf(car.getC_fono4())));
         }else{
          s.addCell(new Label(42, j+1, ""));
         }

         if(car.getC_extension4()!=null){
          s.addCell(new Label(43, j+1, String.valueOf(car.getC_extension4())));
         }else{
          s.addCell(new Label(43, j+1, ""));
         }

         if(car.getC_tipofono5()!=null){
          s.addCell(new Label(44, j+1, String.valueOf(car.getC_tipofono5())));
         }else{
          s.addCell(new Label(44, j+1, ""));
         }

         if(car.getC_prefijo5()!=null){
          s.addCell(new Label(45, j+1, String.valueOf(car.getC_prefijo5())));
         }else{
          s.addCell(new Label(45, j+1, ""));
         }

         if(car.getC_fono5()!=null){
          s.addCell(new Label(46, j+1, String.valueOf(car.getC_fono5())));
         }else{
          s.addCell(new Label(46, j+1, ""));
         }

         if(car.getC_extension5()!=null){
          s.addCell(new Label(47, j+1, String.valueOf(car.getC_extension5())));
         }else{
          s.addCell(new Label(47, j+1, ""));
         }

         if(car.getC_email()!=null){
          s.addCell(new Label(48, j+1, String.valueOf(car.getC_email())));
         }else{
          s.addCell(new Label(48, j+1, ""));
         }

         if(car.getF_fecha_generacion_registro()!=null){
          s.addCell(new Label(49, j+1, String.valueOf(car.getF_fecha_generacion_registro())));
         }else{
          s.addCell(new Label(49, j+1, ""));
         }

         if(car.getF_fecha_ingreso()!=null){
          s.addCell(new Label(50, j+1, String.valueOf(car.getF_fecha_ingreso()).substring(8, 10) + "/" +
          String.valueOf(car.getF_fecha_ingreso()).substring(5, 7) + "/" +
          String.valueOf(car.getF_fecha_ingreso()).substring(0, 4)));
         }else{
          s.addCell(new Label(50, j+1, ""));
         }

         if(car.getC_oficina2()!=null){
          s.addCell(new Label(51, j+1, String.valueOf(car.getC_oficina2())));
         }else{
          s.addCell(new Label(51, j+1, ""));
         }

         if(car.getC_producto()!=null){
          s.addCell(new Label(52, j+1, String.valueOf(car.getC_producto())));
         }else{
          s.addCell(new Label(52, j+1, ""));
         }

         if(car.getC_marca()!=null){
          s.addCell(new Label(53, j+1, String.valueOf(car.getC_marca())));
         }else{
          s.addCell(new Label(53, j+1, ""));
         }

         if(car.getC_tipo_telefono1()!=null){
          s.addCell(new Label(54, j+1, String.valueOf(car.getC_tipo_telefono1())));
         }else{
          s.addCell(new Label(54, j+1, ""));
         }

         if(car.getC_prefijo_telefono1()!=null){
          s.addCell(new Label(55, j+1, String.valueOf(car.getC_prefijo_telefono1())));
         }else{
          s.addCell(new Label(55, j+1, ""));
         }

         if(car.getC_telefono1()!=null){
          s.addCell(new Label(56, j+1, String.valueOf(car.getC_telefono1())));
         }else{
         s.addCell(new Label(56, j+1, ""));
         }

         if(car.getC_extencion1()!=null){
          s.addCell(new Label(57, j+1, String.valueOf(car.getC_extencion1())));
         }else{
          s.addCell(new Label(57, j+1, ""));
         }

         if(car.getC_tipo_telefono2()!=null){
          s.addCell(new Label(58, j+1, String.valueOf(car.getC_tipo_telefono2())));
         }else{
          s.addCell(new Label(58, j+1, ""));
         }

         if(car.getC_prefijo_telefono2()!=null){
          s.addCell(new Label(59, j+1, String.valueOf(car.getC_prefijo_telefono2())));
         }else{
          s.addCell(new Label(59, j+1, ""));
         }

         if(car.getC_telefono2()!=null){
          s.addCell(new Label(60, j+1, String.valueOf(car.getC_telefono2())));
         }else{
          s.addCell(new Label(60, j+1, ""));
         }

         if(car.getC_extencion2()!=null){
          s.addCell(new Label(61, j+1, String.valueOf(car.getC_extencion2())));
         }else{
          s.addCell(new Label(61, j+1, ""));
         }

         if(car.getC_direccion1()!=null){
          s.addCell(new Label(62, j+1, String.valueOf(car.getC_direccion1())));
         }else{
          s.addCell(new Label(62, j+1, ""));
         }

         if(car.getC_departamento1()!=null){
          s.addCell(new Label(63, j+1, String.valueOf(car.getC_departamento1())));
         }else{
          s.addCell(new Label(63, j+1, ""));
         }

         if(car.getC_provincia1()!=null){
          s.addCell(new Label(64, j+1, String.valueOf(car.getC_provincia1())));
         }else{
          s.addCell(new Label(64, j+1, ""));
         }

         if(car.getC_distrito1()!=null){
          s.addCell(new Label(65, j+1, String.valueOf(car.getC_distrito1())));
         }else{
          s.addCell(new Label(65, j+1, ""));
         }

         if(car.getC_direccion2()!=null){
          s.addCell(new Label(66, j+1, String.valueOf(car.getC_direccion2())));
         }else{
          s.addCell(new Label(66, j+1, ""));
         }

         if(car.getC_departamento2()!=null){
          s.addCell(new Label(67, j+1, String.valueOf(car.getC_departamento2())));
         }else{
          s.addCell(new Label(67, j+1, ""));
         }

         if(car.getC_provincia2()!=null){
          s.addCell(new Label(68, j+1, String.valueOf(car.getC_provincia2())));
         }else{
          s.addCell(new Label(68, j+1, ""));
         }

         if(car.getC_distrito2()!=null){
          s.addCell(new Label(69, j+1, String.valueOf(car.getC_distrito2())));
         }else{
          s.addCell(new Label(69, j+1, ""));
         }

         if(car.getF_ult_fecasig()!=null){
          s.addCell(new Label(70, j+1, String.valueOf(car.getF_ult_fecasig()).substring(8, 10) + "/" +
          String.valueOf(car.getF_ult_fecasig()).substring(5, 7) + "/" +
          String.valueOf(car.getF_ult_fecasig()).substring(0, 4)));
         }else{
          s.addCell(new Label(70, j+1, ""));
         }

         if(car.getC_ult_id_codtcon()!=null){
          s.addCell(new Label(71, j+1, String.valueOf(car.getC_ult_id_codtcon())));
         }else{
          s.addCell(new Label(71, j+1, ""));
         }

         if(car.getC_ult_c_destcon()!=null){
          s.addCell(new Label(72, j+1, String.valueOf(car.getC_ult_c_destcon())));
         }else{
          s.addCell(new Label(72, j+1, ""));
         }


         if(car.getC_ult_id_codtres()!=null){
         s.addCell(new Label(73, j+1, String.valueOf(car.getC_ult_id_codtres())));
         }else{
         s.addCell(new Label(73, j+1, ""));
         }

         if(car.getC_ult_c_destres()!=null){
          s.addCell(new Label(74, j+1, String.valueOf(car.getC_ult_c_destres())));
         }else{
          s.addCell(new Label(74, j+1, ""));
         }


         if(car.getF_ult_fecresp()!=null){
         s.addCell(new Label(75, j+1, String.valueOf(car.getF_ult_fecresp()).substring(8, 10) + "/" +
         String.valueOf(car.getF_ult_fecresp()).substring(5, 7) + "/" +
         String.valueOf(car.getF_ult_fecresp()).substring(0, 4)));
         }else{
         s.addCell(new Label(75, j+1, ""));
         }

         if(car.getC_ult_id_codusu()!=null){
          s.addCell(new Label(76, j+1, String.valueOf(car.getC_ult_id_codusu())));
         }else{
          s.addCell(new Label(76, j+1, ""));
         }

         if(car.getC_ult_c_nomusu()!=null){
          s.addCell(new Label(77, j+1, String.valueOf(car.getC_ult_c_nomusu())));
         }else{
          s.addCell(new Label(77, j+1, ""));
         }

         if(car.getIn_return()!=null){
          s.addCell(new Label(78, j+1, String.valueOf(car.getIn_return())));
         }else{
          s.addCell(new Label(78, j+1, ""));
         }


       }
         w.write();
         w.close();
         out.close();

        JOptionPane.showMessageDialog(null,"Reporte Terminado");

      } catch(Exception e) {
        JOptionPane.showMessageDialog(null, "Error en la migracion : " + e.getMessage());
        jProgressBar1.setValue(0);
      }
    }//GEN-LAST:event_btn_importarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             frm_importar_car frm=new frm_importar_car( new javax.swing.JFrame(),true);
             frm.setSize(500, 240);
             frm.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_importar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane lbl_ruta;
    // End of variables declaration//GEN-END:variables

}
