
package FORMULARIOS;

import BEANS.Cartera;
import BEANS.Gestion;
import BEANS.Globales;
import BEANS.Usuario;
import java.awt.event.KeyEvent;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Sheet;
import jxl.Workbook;
import jxl.format.Colour;
import jxl.format.UnderlineStyle;
import jxl.write.Label;
import jxl.write.WritableCellFormat;
import jxl.write.WritableFont;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;


public class frm_cartera_Dist extends javax.swing.JDialog {

    File arch;

    void cargar(){
    try{

    cbo_producto.removeAllItems();
    cbo_producto.addItem("COMERCIAL");
    cbo_producto.addItem("CONSUMO");
    cbo_producto.addItem("HIPOTECARIO");
    cbo_producto.addItem("TARJETA");
    cbo_producto.addItem("[Todos]");
    cbo_producto.setSelectedItem("[Todos]");

    cbo_ope1.removeAllItems();
    cbo_ope2.removeAllItems();
    cbo_distrito.removeAllItems();
    cbo_usuario.removeAllItems();
    cbo_tipres.removeAllItems();
    cbo_tipcon.removeAllItems();
    cbo_territorio.removeAllItems();

    Usuario usu=new Usuario();
    Cartera car=new Cartera();
    ArrayList lista=new ArrayList();
    lista=usu.listado_teleoperadores();

    DefaultListModel l=new DefaultListModel();

    //LLENADO EL JLIST Y EL COMBO USUARIO A LA VEZ
    for(int i=0;i<lista.size();i++){
    usu=(Usuario)lista.get(i);
    l.addElement(usu.getId_codusu() + " - " + usu.getC_nomusu());
    cbo_usuario.addItem(usu.getId_codusu() + " - " + usu.getC_nomusu());
    }jList1.setModel(l);
    cbo_usuario.addItem("Todos");
    cbo_usuario.setSelectedItem("Todos");
    //HASTA AQUI

    lista.clear();
    lista=car.datos_territorio();

    for(int i=0;i<lista.size();i++){
    car=(Cartera)lista.get(i);
    cbo_territorio.addItem(car.getC_territorio());    
    }cbo_territorio.addItem("Todos");
     cbo_territorio.setSelectedItem("Todos");
    lista.clear();

    lista=car.datos_distprov();
    for(int i=0;i<lista.size();i++){
    car=(Cartera)lista.get(i);
    cbo_distrito.addItem(car.getC_distprov());
    }cbo_distrito.addItem("Todos");
    cbo_distrito.setSelectedItem("Todos");

    cbo_tipcon.addItem("01 - Contacto Directo");
    cbo_tipcon.addItem("02 - Contacto Indirecto");
    cbo_tipcon.addItem("03 - No Contacto");
    cbo_tipcon.addItem("Todos");
    cbo_tipcon.setSelectedItem("Todos");

    cbo_ope1.addItem(">");
    cbo_ope1.addItem("<");
    cbo_ope1.addItem(">=");
    cbo_ope1.addItem("<=");
    cbo_ope1.addItem("Entre");

    cbo_ope2.addItem(">");
    cbo_ope2.addItem("<");
    cbo_ope2.addItem(">=");
    cbo_ope2.addItem("<=");
    cbo_ope2.addItem("Entre");

    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }


    public frm_cartera_Dist(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ((javax.swing.JSpinner.DateEditor)dtpf_fecpro.getEditor()).getTextField().setEditable(false);
        this.cargar();        
        txtn_canreg.setEditable(false);
        jList1.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dtpf_fecpro = new javax.swing.JSpinner();
        cbo_territorio = new javax.swing.JComboBox();
        cbo_ope1 = new javax.swing.JComboBox();
        cbo_usuario = new javax.swing.JComboBox();
        cbo_tipres = new javax.swing.JComboBox();
        chk_gestion = new javax.swing.JCheckBox();
        chk_arrastes = new javax.swing.JCheckBox();
        chk_contnue = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtc_numdoc = new javax.swing.JTextField();
        txtc_nomcont = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbo_tipcon = new javax.swing.JComboBox();
        cbo_ope2 = new javax.swing.JComboBox();
        txtn_diasini = new javax.swing.JTextField();
        txtn_diasfin = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtn_totini = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtn_totfin = new javax.swing.JTextField();
        cbo_distrito = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lbl_ruta = new javax.swing.JTextPane();
        lbln_regcar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btn_mostrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        rdb_all = new javax.swing.JRadioButton();
        rdbcant = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lbl_nroreg = new javax.swing.JTextField();
        txtn_canreg = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbo_producto = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Distribución de Cartera");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios de Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.blue)); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel2.setText("F. Proceso :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(390, 27, 75, 16);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel3.setText("Territorio :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(390, 50, 75, 16);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel4.setText("Deuda Total :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(390, 76, 85, 16);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel5.setText("Operador :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(390, 101, 75, 16);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel6.setText("T. Resp :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(390, 126, 75, 16);

        dtpf_fecpro.setModel(new javax.swing.SpinnerDateModel());
        dtpf_fecpro.setEditor(new javax.swing.JSpinner.DateEditor(dtpf_fecpro, "dd/MM/yyyy"));
        jPanel1.add(dtpf_fecpro);
        dtpf_fecpro.setBounds(474, 23, 90, 22);

        cbo_territorio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_territorio);
        cbo_territorio.setBounds(474, 48, 210, 22);

        cbo_ope1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_ope1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_ope1ActionPerformed(evt);
            }
        });
        jPanel1.add(cbo_ope1);
        cbo_ope1.setBounds(474, 73, 60, 22);

        cbo_usuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_usuario);
        cbo_usuario.setBounds(474, 98, 210, 22);

        cbo_tipres.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_tipres);
        cbo_tipres.setBounds(474, 123, 485, 22);

        chk_gestion.setFont(new java.awt.Font("Ubuntu", 0, 14));
        chk_gestion.setText("Cartera Gestionada");
        jPanel1.add(chk_gestion);
        chk_gestion.setBounds(810, 147, 150, 24);

        chk_arrastes.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        chk_arrastes.setText("Clientes con Arrastres");
        jPanel1.add(chk_arrastes);
        chk_arrastes.setBounds(387, 147, 165, 24);

        chk_contnue.setFont(new java.awt.Font("Ubuntu", 0, 14));
        chk_contnue.setText("Clientes con Contratos Nuevos");
        jPanel1.add(chk_contnue);
        chk_contnue.setBounds(570, 147, 228, 24);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel7.setText("Nº Docu :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(574, 25, 65, 16);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel8.setText("Nombre :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(728, 25, 62, 16);
        jPanel1.add(txtc_numdoc);
        txtc_numdoc.setBounds(638, 22, 80, 22);
        jPanel1.add(txtc_nomcont);
        txtc_nomcont.setBounds(790, 22, 220, 22);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel9.setText("Distrito Prov :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(695, 50, 88, 16);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel10.setText("Dias Venc :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(700, 76, 72, 16);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel11.setText("T.Contacto :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(698, 101, 82, 16);

        cbo_tipcon.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_tipcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_tipconActionPerformed(evt);
            }
        });
        jPanel1.add(cbo_tipcon);
        cbo_tipcon.setBounds(780, 97, 180, 22);

        cbo_ope2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_ope2);
        cbo_ope2.setBounds(775, 73, 60, 22);
        jPanel1.add(txtn_diasini);
        txtn_diasini.setBounds(838, 73, 50, 22);
        jPanel1.add(txtn_diasfin);
        txtn_diasfin.setBounds(940, 73, 50, 22);

        jLabel12.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jLabel12.setText("Hasta :");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(893, 76, 45, 16);
        jPanel1.add(txtn_totini);
        txtn_totini.setBounds(538, 73, 50, 22);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel13.setText("Hasta :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(595, 76, 45, 16);
        jPanel1.add(txtn_totfin);
        txtn_totfin.setBounds(640, 73, 50, 22);

        cbo_distrito.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbo_distrito);
        cbo_distrito.setBounds(784, 48, 230, 22);

        jScrollPane3.setViewportView(jList2);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 40, 102, 120);

        jButton6.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jButton6.setText("Archivo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(115, 40, 80, 28);

        jButton7.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jButton7.setText("Añadir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(200, 40, 80, 28);

        jButton8.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jButton8.setText("Limpiar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(284, 40, 80, 28);

        jLabel16.setText("Codcent");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 20, 60, 18);

        lbl_ruta.setBackground(java.awt.Color.white);
        jScrollPane4.setViewportView(lbl_ruta);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(116, 70, 250, 65);

        lbln_regcar.setEditable(false);
        lbln_regcar.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        lbln_regcar.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        lbln_regcar.setText("0");
        jPanel1.add(lbln_regcar);
        lbln_regcar.setBounds(116, 140, 55, 22);

        jLabel15.setText("Registros Cargados");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(175, 142, 140, 18);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(250, 55, 1030, 175);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setBackground(new java.awt.Color(255, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selec.", "f_fproceso", "c_codcent", "c_nrodoc", "c_nombre", "c_territorio", "num_contr", "dve_max", "tot_sol", "tot_dol", "tot_gen", "f_fecasig_ult", "id_codtcon", "c_destcon", "id_codtres", "c_destres", "f_fecprog_ult", "id_codusu", "c_nomusu", "c_arrastre", "b_flgasi", "b_flgrec", "n_numrec", "f_fecing", "c_flgnuev"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(90);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(95);
        jTable2.getColumnModel().getColumn(3).setPreferredWidth(95);
        jTable2.getColumnModel().getColumn(4).setPreferredWidth(200);
        jTable2.getColumnModel().getColumn(11).setPreferredWidth(90);
        jTable2.getColumnModel().getColumn(13).setPreferredWidth(160);
        jTable2.getColumnModel().getColumn(14).setPreferredWidth(85);
        jTable2.getColumnModel().getColumn(15).setPreferredWidth(270);
        jTable2.getColumnModel().getColumn(16).setPreferredWidth(90);
        jTable2.getColumnModel().getColumn(17).setPreferredWidth(120);
        jTable2.getColumnModel().getColumn(18).setPreferredWidth(160);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 290, 1267, 310);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btn_mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mostrar.JPG"))); // NOI18N
        btn_mostrar.setText("Mostrar");
        btn_mostrar.setFocusable(false);
        btn_mostrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mostrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_mostrar);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/traspaso.JPG"))); // NOI18N
        jButton2.setText("Asignar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/excel.JPG"))); // NOI18N
        jButton3.setText("Exportar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/wzdelete.JPG"))); // NOI18N
        jButton4.setText("Quitar");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        getContentPane().add(jToolBar1);
        jToolBar1.setBounds(0, 0, 1290, 44);

        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(10, 260, 1268, 22);

        buttonGroup1.add(rdb_all);
        rdb_all.setFont(new java.awt.Font("Ubuntu", 0, 14));
        rdb_all.setText("Seleccionar Todos");
        rdb_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_allActionPerformed(evt);
            }
        });
        getContentPane().add(rdb_all);
        rdb_all.setBounds(10, 232, 142, 24);

        buttonGroup1.add(rdbcant);
        rdbcant.setFont(new java.awt.Font("Ubuntu", 0, 14));
        rdbcant.setText("Ingresar Cantidad Seleccionar");
        rdbcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbcantActionPerformed(evt);
            }
        });
        getContentPane().add(rdbcant);
        rdbcant.setBounds(155, 232, 215, 24);

        jList1.setBackground(new java.awt.Color(255, 255, 204));
        jList1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccione Operador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), java.awt.Color.blue)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 230, 160);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel14.setText("Nº Registros :");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(15, 7, 90, 16);

        lbl_nroreg.setEditable(false);
        lbl_nroreg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        lbl_nroreg.setText("0");
        jPanel3.add(lbl_nroreg);
        lbl_nroreg.setBounds(105, 5, 60, 22);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 610, 1290, 30);

        txtn_canreg.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtn_canreg.setText("0");
        txtn_canreg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtn_canregKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtn_canregKeyPressed(evt);
            }
        });
        getContentPane().add(txtn_canreg);
        txtn_canreg.setBounds(380, 233, 59, 22);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 14));
        jLabel1.setText("Producto :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(525, 235, 70, 16);

        cbo_producto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbo_producto);
        cbo_producto.setBounds(600, 233, 300, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_tipconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_tipconActionPerformed
        try{
        String id_codtcon="";
        if(cbo_tipcon.getSelectedItem()!="Todos"){
        id_codtcon=String.valueOf(cbo_tipcon.getSelectedItem()).substring(0, 2);
        }else{
        id_codtcon="";
        }

        cbo_tipres.removeAllItems();
        Gestion llm=new Gestion();
        ArrayList lista=new ArrayList();
        lista=llm.Respuesta_llam(id_codtcon);

        for(int i=0;i<lista.size();i++){
        llm=(Gestion)lista.get(i);
        cbo_tipres.addItem(llm.getId_codtres() + " - " + llm.getC_destres());
        }cbo_tipres.addItem("Todos");
        cbo_tipres.setSelectedItem("Todos");

        }catch(Exception ioE){

        }
}//GEN-LAST:event_cbo_tipconActionPerformed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
    try{
    Globales glo=new Globales();
    Cartera car=new Cartera();
    SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
    String f_fproceso, id_codper, c_nrodoc,c_nombre, c_territorio, id_codusu,id_codtcon,
    id_codtres,c_arrastre="", c_distprov, b_flgasi,b_flgrec, producto, poper_dv="",
    pval_dv_a="", pval_dv_b="", poper_dt="", pval_dt_a="", pval_dt_b="", str="", strFilter="";

    f_fproceso=sdf.format(dtpf_fecpro.getValue()) + " 00:00:00.000";
    id_codper=glo.getId_codper();
    c_nrodoc=txtc_numdoc.getText().trim();
    c_nombre=txtc_nomcont.getText().trim();

    if(Integer.parseInt(lbln_regcar.getText()) > 0){
        for(int i= 0; i<Integer.parseInt(lbln_regcar.getText());i++){
            jList2.setSelectedIndex(i);
            strFilter = strFilter + "'" + jList2.getSelectedValue() + "',";
        }
        strFilter=strFilter.substring(0, strFilter.length() - 1);
        strFilter=" and ic_codcent in (" + strFilter + ")";
    }

    str= " where if_fproceso='" + f_fproceso + "'";

    if(cbo_territorio.getSelectedItem()=="Todos"){
    c_territorio="";
    }else{
    c_territorio=cbo_territorio.getSelectedItem().toString();
    }

    if(cbo_distrito.getSelectedItem()=="Todos"){
    c_distprov="";
    }else{
     c_distprov=cbo_distrito.getSelectedItem().toString();
    }

    if(chk_gestion.isSelected()){
    b_flgasi="1";
    b_flgrec="1";
    }else{
    b_flgasi="0";
    b_flgrec="0";
    }

    if(cbo_producto.getSelectedItem()!="[Todos]"){
     producto= String.valueOf(cbo_producto.getSelectedItem());
    }else{
     producto="";
    }

    if(cbo_usuario.getSelectedItem()!="Todos"){
     int index=String.valueOf(cbo_usuario.getSelectedItem()).indexOf(" - ", 0);
     id_codusu = String.valueOf(cbo_usuario.getSelectedItem()).substring(0, index);
    }else{
     id_codusu = "";
    }

    if(cbo_tipcon.getSelectedItem()!= "Todos"){
     id_codtcon = String.valueOf(cbo_tipcon.getSelectedItem()).substring(0, 2);
    }else{
     id_codtcon="";
    }

    if(cbo_tipres.getSelectedItem()!="Todos"){
     id_codtres = String.valueOf(cbo_tipres.getSelectedItem()).substring(0, 4).trim();
    }else{
     id_codtres="";
    }

    if(chk_arrastes.isSelected()){
      c_arrastre = "1" ;
    }else{
      c_arrastre="0";
    }

    if(chk_contnue.isSelected()){
       str = str + " and ic_flgnuev = '1'";
    }

    if(txtn_totini.getText().trim().length()>0){
       poper_dt= String.valueOf(cbo_ope1.getSelectedItem());
       pval_dt_a=txtn_totini.getText().trim();
       pval_dt_b=txtn_totfin.getText().trim();
    }

    if(txtn_diasini.getText().trim().length()>0) {
       poper_dv= String.valueOf(cbo_ope2.getSelectedItem());
       pval_dv_a=txtn_diasini.getText().trim();
       pval_dv_b=txtn_diasfin.getText().trim();
    }

    str = str + strFilter;
 
    ArrayList lista=new ArrayList();
    lista=car.listado_cartera(f_fproceso, id_codper, c_nrodoc, c_nombre, c_territorio, 
    c_distprov, b_flgasi, b_flgrec, id_codusu,id_codtcon, id_codtres,poper_dv,
    pval_dv_a, pval_dv_b, poper_dt, pval_dt_a, pval_dt_b,producto,c_arrastre, str);
    lbl_nroreg.setText(lista.size() + "");
    
    DefaultTableModel m=(DefaultTableModel)jTable2.getModel();
    m.setNumRows(lista.size());
    for(int i=0;i<lista.size();i++){
    car=(Cartera)lista.get(i);
    m.setValueAt(false, i, 0);
    m.setValueAt(String.valueOf(car.getF_fproceso()).substring(8, 10) + "/" +
    String.valueOf(car.getF_fproceso()).substring(5, 7) + "/" +
    String.valueOf(car.getF_fproceso()).substring(0, 4), i, 1);
    m.setValueAt(car.getC_codcent(), i, 2);
    m.setValueAt(car.getC_nrodoc(), i, 3);
    m.setValueAt(car.getC_nombre(), i, 4);
    m.setValueAt(car.getC_territorio(), i, 5);
    m.setValueAt(car.getNum_contr(), i, 6);
    m.setValueAt(car.getDve_max(), i, 7);
    m.setValueAt(car.getTot_sol(), i, 8);
    m.setValueAt(car.getTot_dol(), i, 9);
    m.setValueAt(car.getTot_gen(), i, 10);

    if(car.getF_fecasig_ult()!=null){
     m.setValueAt(String.valueOf(car.getF_fecasig_ult()).substring(8, 10) + "/" +
     String.valueOf(car.getF_fecasig_ult()).substring(5, 7) + "/" +
     String.valueOf(car.getF_fecasig_ult()).substring(0, 4), i, 11);
    }else{
     m.setValueAt(car.getF_fecasig_ult(), i, 11);
    }

    
    m.setValueAt(car.getId_codtcon(), i, 12);
    m.setValueAt(car.getC_destcon(), i, 13);
    m.setValueAt(car.getId_codtres(), i, 14);
    m.setValueAt(car.getC_destres(), i, 15);

    if(car.getF_fecprog_ult()!=null){
     m.setValueAt(String.valueOf(car.getF_fecprog_ult()).substring(8, 10) + "/" +
     String.valueOf(car.getF_fecprog_ult()).substring(5, 7) + "/" +
     String.valueOf(car.getF_fecprog_ult()).substring(0, 4), i, 16);
    }else{
     m.setValueAt(car.getF_fecprog_ult(), i, 16);
    }

    
    m.setValueAt(car.getId_codusu(), i, 17);
    m.setValueAt(car.getC_nomusu(), i, 18);
    m.setValueAt(car.getC_provision(), i, 19);
    m.setValueAt(car.getB_flgasi(), i, 20);
    m.setValueAt(car.getB_flgrec(), i, 21);
    m.setValueAt(car.getN_numrec(), i, 22);

    if(car.getF_fecing()!=null){
     m.setValueAt(String.valueOf(car.getF_fecing()).substring(8, 10) + "/" +
     String.valueOf(car.getF_fecing()).substring(5, 7) + "/" +
     String.valueOf(car.getF_fecing()).substring(0, 4), i, 23);
    }else{
     m.setValueAt(car.getF_fecing(), i, 23);
    }

    
     m.setValueAt(car.getC_flgnuev(), i, 24);
    }this.jTable2.setModel(m);   
    }catch(Exception e){
    JOptionPane.showMessageDialog(null, e.getMessage());
    }
}//GEN-LAST:event_btn_mostrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try{
     String codcent, f_fproceso, id_codusu, b_flgrec;
     int index=String.valueOf(jList1.getSelectedValue()).indexOf(" - ", 0);
     id_codusu=String.valueOf(jList1.getSelectedValue()).substring(0, index);

     Cartera car=new Cartera();

     int res=JOptionPane.showConfirmDialog(null, "¿Esta Seguro de Asignar Registros al Usuario:","Informacion",JOptionPane.YES_NO_OPTION);
     if(res==1){
     return;    
     }else{
     for(int i=0;i<jTable2.getRowCount();i++){
     boolean estado=false;
     estado=Boolean.parseBoolean(jTable2.getValueAt(i,0) + "");
     if(estado==true){
     codcent=String.valueOf(jTable2.getValueAt(i, 2));

     f_fproceso=String.valueOf(jTable2.getValueAt(i, 1)).substring(6, 10) + "-" +
     String.valueOf(jTable2.getValueAt(i, 1)).substring(3, 5) + "-" +
     String.valueOf(jTable2.getValueAt(i, 1)).substring(0, 2) + " 00:00:00.000";

     b_flgrec=String.valueOf(jTable2.getValueAt(i, 20));
     
     car.Asignacion_Cartera(codcent,f_fproceso ,id_codusu, "01", b_flgrec);
     }
     }btn_mostrarActionPerformed(evt);
     }
     }catch(Exception ioE){
     JOptionPane.showMessageDialog(null, ioE);
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtn_canregKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn_canregKeyTyped
      int k=(int)evt.getKeyChar();
      //if (k >= 97 && k <= 122 || k>=65 && k<=90){
      if (k >= 58 && k <= 122 || k>=33 && k<=47){
      evt.setKeyChar((char)KeyEvent.VK_CLEAR);
      }
}//GEN-LAST:event_txtn_canregKeyTyped

    private void txtn_canregKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtn_canregKeyPressed
      try{

      if(evt.getKeyCode()==(char)KeyEvent.VK_ENTER){

      if(txtn_canreg.getText().trim().length()==0){
      JOptionPane.showMessageDialog(null, "Ingrese cantidad de registros a seleccionar");
      return;
      }

      if(jTable2.getRowCount()<Integer.parseInt(txtn_canreg.getText()) || jTable2.getRowCount()==0){
      JOptionPane.showMessageDialog(null, "No hay registros a seleccionar");
      return;
      }

      boolean check1=false;
      for(int i=0;i<jTable2.getRowCount();i++){
      jTable2.setValueAt(check1, i, 0);
      }

      boolean check2=true;
      for(int i=0;i<Integer.parseInt(txtn_canreg.getText());i++){
      jTable2.setValueAt(check2, i, 0);
      }
      }

     }catch(Exception e){
      JOptionPane.showMessageDialog(null, e.getMessage());
     }
}//GEN-LAST:event_txtn_canregKeyPressed

    private void rdb_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_allActionPerformed
    boolean check_act=true;
       boolean check_ina=false;
       if(rdb_all.isSelected()){
        for(int i=0;i<jTable2.getRowCount();i++){
         jTable2.setValueAt(check_act, i, 0);
        }
       }else{
        for(int i=0;i<jTable2.getRowCount();i++){
         jTable2.setValueAt(check_ina, i, 0);
        }
       }
}//GEN-LAST:event_rdb_allActionPerformed

    private void rdbcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbcantActionPerformed
     if(rdbcant.isSelected()){
      txtn_canreg.setEditable(true);
     }else{
      txtn_canreg.setEditable(false);
     }
    }//GEN-LAST:event_rdbcantActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       frm_Cartera_Quit frm = new frm_Cartera_Quit(new javax.swing.JFrame(), true);
       frm.setSize(850,530);
       frm.setLocation(50, 20);
       frm.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
        JFileChooser caja=new JFileChooser();
        caja.showSaveDialog(null);
        File arch=caja.getSelectedFile();

        if(arch==null){
        return;
        }

        DataOutputStream out=new DataOutputStream(new FileOutputStream(arch + ".xls"));
        WritableWorkbook w = Workbook.createWorkbook(out);
        WritableSheet s = w.createSheet("reporte", 0);
        WritableFont headersfont=new WritableFont(WritableFont.ARIAL, 10, WritableFont.BOLD, false, UnderlineStyle.NO_UNDERLINE, Colour.WHITE);
        WritableCellFormat headersformat=new WritableCellFormat(headersfont);
        headersformat.setBackground(Colour.ORANGE);
        
        s.addCell(new Label(0, 0, String.valueOf("F_fproceso"),headersformat));
        s.addCell(new Label(1, 0, String.valueOf("C_codcent"),headersformat));
        s.addCell(new Label(2, 0, String.valueOf("C_nrodoc"),headersformat));
        s.addCell(new Label(3, 0, String.valueOf("C_nombre"),headersformat));
        s.addCell(new Label(4, 0, String.valueOf("C_territorio"),headersformat));
        s.addCell(new Label(5, 0, String.valueOf("Num_contr"),headersformat));
        s.addCell(new Label(6, 0, String.valueOf("Dve_max"),headersformat));
        s.addCell(new Label(7, 0, String.valueOf("Tot_sol"),headersformat));
        s.addCell(new Label(8, 0, String.valueOf("Tot_dol"),headersformat));
        s.addCell(new Label(9, 0, String.valueOf("Tot_gen"),headersformat));
        s.addCell(new Label(10, 0, String.valueOf("F_fecasig_ult"),headersformat));
        s.addCell(new Label(11, 0, String.valueOf("Id_codtcon"),headersformat));
        s.addCell(new Label(12, 0, String.valueOf("C_destcon"),headersformat));
        s.addCell(new Label(13, 0, String.valueOf("Id_codtres"),headersformat));
        s.addCell(new Label(14, 0, String.valueOf("C_destres"),headersformat));
        s.addCell(new Label(15, 0, String.valueOf("F_fecprog_ult"),headersformat));
        s.addCell(new Label(16, 0, String.valueOf("Id_codusu"),headersformat));
        s.addCell(new Label(17, 0, String.valueOf("C_nomusu"),headersformat));
        s.addCell(new Label(18, 0, String.valueOf("C_tarrastre"),headersformat));
        s.addCell(new Label(19, 0, String.valueOf("B_flgasi"),headersformat));
        s.addCell(new Label(20, 0, String.valueOf("B_flgrec"),headersformat));
        s.addCell(new Label(21, 0, String.valueOf("N_numrec"),headersformat));
        s.addCell(new Label(22, 0, String.valueOf("F_fecing"),headersformat));
        s.addCell(new Label(23, 0, String.valueOf("C_flgnuev"),headersformat));

        for(int i=0;i<jTable2.getRowCount();i++){

              for(int j=1;j<jTable2.getColumnCount();j++){
                 Object objeto=jTable2.getValueAt(i,j);
                 if(objeto!=null){
                    if(j==6 || j==7){
                      s.addCell(new jxl.write.Number(j-1, i+1, Integer.parseInt(objeto + "")));
                    }else{
                      s.addCell(new Label(j-1, i+1, String.valueOf(objeto)));
                    }
                 }else{
                   s.addCell(new Label(j-1, i+1, ""));
                 }
               }
            }

            w.write();
            w.close();
            out.close();

           JOptionPane.showMessageDialog(null,"Reporte Terminado");

        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbo_ope1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_ope1ActionPerformed
      try{
      if(cbo_ope1.getSelectedItem().equals("Entre")){
       txtn_totfin.setText("");
       txtn_totini.setEnabled(true);
       txtn_totfin.setEnabled(true);
      }else{
       txtn_totfin.setText("");
       txtn_totini.setEnabled(true);
       txtn_totfin.setEnabled(false);
      }
      }catch(Exception e){
      
      }
    }//GEN-LAST:event_cbo_ope1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            String ruta;
            JFileChooser caja=new JFileChooser();
            caja.showOpenDialog(null);
            arch=caja.getSelectedFile();

            if(arch==null){
                return;
            }
            ruta=arch.getPath();
            lbl_ruta.setText(ruta);
        }catch(Exception e){
            JOptionPane.showConfirmDialog(null, e);
        }
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        try{
            if(lbl_ruta.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Seleccione Archivo a importar");
                return;
            }

            Workbook wb = Workbook.getWorkbook(arch);
            Sheet sheet = wb.getSheet(0);
            int rows = sheet.getRows();

            String nrodoc="";
            DefaultListModel l=new DefaultListModel();
            for(int i=0;i<rows;i++){
                nrodoc=sheet.getCell(0, i).getContents().trim();
                l.addElement(nrodoc);
            }jList2.setModel(l);
            lbln_regcar.setText(l.size() + "");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        } 
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        lbl_ruta.setText("");
        jList2.setModel(new DefaultListModel());
}//GEN-LAST:event_jButton8ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frm_cartera_Dist dialog = new frm_cartera_Dist(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
                dialog.setSize(940, 700);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mostrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbo_distrito;
    private javax.swing.JComboBox cbo_ope1;
    private javax.swing.JComboBox cbo_ope2;
    private javax.swing.JComboBox cbo_producto;
    private javax.swing.JComboBox cbo_territorio;
    private javax.swing.JComboBox cbo_tipcon;
    private javax.swing.JComboBox cbo_tipres;
    private javax.swing.JComboBox cbo_usuario;
    private javax.swing.JCheckBox chk_arrastes;
    private javax.swing.JCheckBox chk_contnue;
    private javax.swing.JCheckBox chk_gestion;
    private javax.swing.JSpinner dtpf_fecpro;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField lbl_nroreg;
    private javax.swing.JTextPane lbl_ruta;
    private javax.swing.JTextField lbln_regcar;
    private javax.swing.JRadioButton rdb_all;
    private javax.swing.JRadioButton rdbcant;
    private javax.swing.JTextField txtc_nomcont;
    private javax.swing.JTextField txtc_numdoc;
    private javax.swing.JTextField txtn_canreg;
    private javax.swing.JTextField txtn_diasfin;
    private javax.swing.JTextField txtn_diasini;
    private javax.swing.JTextField txtn_totfin;
    private javax.swing.JTextField txtn_totini;
    // End of variables declaration//GEN-END:variables

}
